### PR TITLE
test: get operator logs on failed specs

### LINKED ISSUE #960: Add operator logs on cluster failure
We are finding an entanglement in the E2E test suite where a failure
in a spec may result in another spec that was in transit failing due
to timeout waiting for a cluster to be ready.
It would be good to get the recent operator logs in such cases.

### PR DESCRIPTION
**Pull request by jsilvela**
To help investigate E2E test failures, we start tailing the operator
logs at the beginning of each spec, in a goroutine.
If the spec fails, we display the logs on Ginkgo and store them in a file.

Closes #960 

Signed-off-by: Jaime Silvela <jaime.silvela@enterprisedb.com>

### CODE REVIEW

File: tests/e2e/hibernation_test.go [hunk 1]
```diff
@@ -107,7 +107,8 @@ var _ = Describe("Cluster Hibernation with plugin", func() {
 		verifySummaryInHibernationStatus := func(clusterName string, message hibernateSatusMessage) {
 			statusOut := getHibernationStatusInJSON(namespace, clusterName)
 			actualStatus := statusOut[string(summaryInStatus)].(map[string]interface{})["status"].(string)
-			Expect(strings.Contains(string(message), actualStatus)).Should(BeEquivalentTo(true), statusOut)
+			Expect(strings.Contains(string(message), actualStatus)).Should(BeEquivalentTo(true),
+				actualStatus+"\\not-contained-in\\"+string(message))
```
Comment (jsilvela) [inline tests/e2e/hibernation_test.go:111]: ALSO fixes a Panic in the hibernate test when the `statusOut` provided as context to Ginkgo cannot be cast to string

**Review by litaocdl — APPROVED** [review]

File: tests/e2e/suite_test.go [hunk 2]
```diff
@@ -74,6 +132,24 @@ var _ = BeforeEach(func() {
...
+	var buf bytes.Buffer
+	go func() {
+		// get logs without timestamp parsing; for JSON parseability
+		err = logs.TailPodLogs(context.TODO(), operatorPod, &buf, false)
+		if err != nil {
+			_, _ = fmt.Fprintf(&buf, "Error tailing logs, dumping operator logs: %v\n", err)
+		}
+	}()
+	DeferCleanup(func(ctx SpecContext) {
+		if true {
```
Comment (jsilvela) [inline tests/e2e/suite_test.go:145]:
```suggestion
		if CurrentSpecReport().Failed() {
```

**Review by gbartolini — APPROVED** [review]
