### PR TITLE
fix(bootstrap): clean up the WAL volume before initializing a cluster

### LINKED ISSUE #6264: [Bug]: cleanup pg_wal as well before initializing a PVC
### Is there an existing issue already for this bug?

- [x] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [x] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [x] I have read the troubleshooting guide and I think this is a new bug.

### Contact Details

_No response_

### Version

trunk (main)

### What version of Kubernetes are you using?

1.31

### What is your Kubernetes environment?

Self-managed: kind (evaluation)

### How did you install the operator?

YAML manifest

### What happened?

In #5112, we introduced automation that checks the content of the PGDATA volume before initializing it. If it is not empty, it moves away from the previous data. However, if the WAL files are stored in a separate directory, it misses cleaning up that additional location, potentially resulting in a failed initialization.

We should improve the cleanup procedure and clean any additional volumes as well.

### Cluster resource

```shell

```

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by mnencia**
This patch ensures that the WAL volume is cleaned during the bootstrap as we clean the data directory volume.

Closes #6264 

## Release notes

Fix:
* Include the WAL volume in the clean-up performed during the bootstrap of a cluster.

### CODE REVIEW

**Comment by leonardoce** [comment]
E2e: https://github.com/EnterpriseDB/cloudnative-pg/actions/runs/12160146785

**Review by leonardoce — APPROVED** [review]

File: pkg/management/postgres/initdb.go [hunk 1]
```diff
@@ -132,47 +132,85 @@ type InitInfo struct {
...
 		}
+	}
 
-		return nil
+	if pgWalExists {
+		contextLogger.Info("cleaning up existing PG_WAL directory")
+		if err := fileutils.RemoveDirectory(info.PgWal); err != nil {
+			contextLogger.Error(err, "error while cleaning up existing PG_WAL directory")
+			return err
+		}
```
Comment (jsilvela) [inline pkg/management/postgres/initdb.go:176]: I find this control flow unclear. It's correct, but:
- if the PGDATA is there with a valid pg_control, we exit from this function into the "rename" function.
- if pg_control is NOT there, we RemoveDirectory of the PGDATA in the first conditional, and the possibl RemoveDirectory of the PGWAL in a different loop.

Going to try to propose a clearer flow.

Comment (jsilvela) [reply pkg/management/postgres/initdb.go]: OK, I've refactored this control flow.
Please @mnencia have a look.

**Review by jsilvela — APPROVED** [review]

**Comment by jsilvela** [comment]
E2E: https://github.com/EnterpriseDB/cloudnative-pg/actions/runs/12162857497

**Review by armru — APPROVED** [review]
