### PR TITLE
fix: check recovery backups/snapshots readiness before cluster bootstrap

### LINKED ISSUE #3654: [Bug]: Restoring from not-completed backup gets stuck in an endless reconciliation loop
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Contact Details

_No response_

### Version

1.22.0

### What version of Kubernetes are you using?

1.28

### What is your Kubernetes environment?

Other

### How did you install the operator?

Helm

### What happened?

I am trying to create a new cluster immediately after creating a volume snapshot backup and restoring that backup. Restoring the cluster will initially fail, because the backup is not completed, yet. However, even after completing the backup, the cluster is stuck in a loop of "refusing to create the primary instance while the latest generated serial is not zero" logs.

I believe this worked with 1.21.1. Back then, cnpg would just wait until the backup was completed and then start restoring the cluster.

### Cluster resource

```shell
Name:         staging-cluster
API Version:  postgresql.cnpg.io/v1
Kind:         Cluster
Metadata:
  Creation Timestamp:  2024-01-02T11:31:35Z
  Generation:          1
  Resource Version:    264735064
  UID:                 17b91fc9-e825-4b6f-b4d8-d8a3a7cc5cb1
Spec:
  Affinity:
    Node Selector:
      kubernetes.io/os:                       linux
    Pod Anti Affinity Type:                   preferred
  Bootstrap:
    Recovery:
      Backup:
        Name:    staging-1704195093
      Database:  app
      Owner:     app
  Certificates:
    Client CA Secret:        staging-pg-streaming-replica
    Replication TLS Secret:  staging-pg-streaming-replica
  Enable Superuser Access:   false
  Failover Delay:            0
  Instances:                              1
  Log Level:                              info
  Max Sync Replicas:                      0
  Min Sync Replicas:                      0
  Monitoring:
    Disable Default Queries:  true
    Enable Pod Monitor:       false
  Postgres GID:               70
  Postgres UID:               70
  Postgresql:
    Parameters:
      archive_mode:                 on
      archive_timeout:              5min
      cron.database_name:           app
      cron.use_background_workers:  on
      dynamic_shared_memory_type:   posix
      log_destination:              csvlog
      log_directory:                /controller/log
      log_filename:                 postgres
      log_rotation_age:             0
      log_rotation_size:            0
      log_truncate_on_rotation:     false
      logging_collector:            on
      max_parallel_workers:         32
      max_replication_slots:        32
      max_worker_processes:         32
      shared_memory_type:           mmap
      shared_preload_libraries:
      ssl_max_protocol_version:     TLSv1.3
      ssl_min_protocol_version:     TLSv1.3
      wal_keep_size:                512MB
      wal_receiver_timeout:         5s
      wal_sender_timeout:           5s
    pg_hba:
      hostssl app all all cert
    shared_preload_libraries:
      pg_cron
    Sync Replica Election Constraint:
      Enabled:              false
  Primary Update Method:    restart
  Primary Update Strategy:  unsupervised
  Replication Slots:
    High Availability:
      Enabled:        true
      Slot Prefix:    _cnpg_
    Update Interval:  30
  Resources:
  Smart Shutdown Timeout:  180
  Start Delay:             3600
  Stop Delay:              1800
  Storage:
    Resize In Use Volumes:  true
    Size:                   1000Gi
    Storage Class:          zfs
  Switchover Delay:         3600
Status:
  Certificates:
    Client CA Secret:  staging-pg-streaming-replica
    Expirations:
      staging-cluster-ca:            2024-04-01 11:26:35 +0000 UTC
      staging-cluster-server:        2024-04-01 11:26:35 +0000 UTC
      staging-pg-streaming-replica:  2024-04-01 11:26:05 +0000 UTC
    Replication TLS Secret:                               staging-pg-streaming-replica
    Server Alt DNS Names:
      staging-cluster-rw
      staging-cluster-r
      staging-cluster-ro
    Server CA Secret:             staging-cluster-ca
    Server TLS Secret:            staging-cluster-server
  Cloud Native PG Commit Hash:    86b9dc80
  Cloud Native PG Operator Hash:  411a67468c5e1357d387221ce5b11d906bd33d62324846a8c776d206b6c94162
  Config Map Resource Version:
  Latest Generated Node:  1
  Managed Roles Status:
  Pooler Integrations:
    Pg Bouncer Integration:
  Read Service:  staging-cluster-r
  Secrets Resource Version:
    Application Secret Version:  264735030
    Client Ca Secret Version:    264731831
    Replication Secret Version:  264731831
    Server Ca Secret Version:    264735023
    Server Secret Version:       264735026
  Topology:
    Successfully Extracted:  true
  Write Service:             staging-cluster-rw
Events:
  Type    Reason                       Age   From            Message
  ----    ------                       ----  ----            -------
  Normal  CreatingPodDisruptionBudget  11m   cloudnative-pg  Creating PodDisruptionBudget staging-cluster-primary
  Normal  CreatingServiceAccount       11m   cloudnative-pg  Creating ServiceAccount
  Normal  CreatingRole                 11m   cloudnative-pg  Creating Cluster Role
```

### Relevant log output

```shell
{"level":"info","ts":"2024-01-02T11:31:35Z","logger":"cluster-resource","msg":"default","version":"v1","name":"staging-cluster","namespace":"..."}
{"level":"info","ts":"2024-01-02T11:31:35Z","logger":"cluster-resource","msg":"validate create","version":"v1","name":"staging-cluster","namespace":"..."}
{"level":"info","ts":"2024-01-02T11:31:35Z","msg":"no orphan PVCs found, skipping the restored cluster reconciliation","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"staging-cluster","namespace":"..."},"namespace":"...","name":"staging-cluster","reconcileID":"489fbe7f-5943-4f9d-8c90-7315dc7dcacd","uuid":"7c6810e5-a962-11ee-95b1-0a1a8ddfb0bf"}
{"level":"info","ts":"2024-01-02T11:31:35Z","msg":"The source backup object is not completed, can't continue full recovery","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"staging-cluster","namespace":"..."},"namespace":"...","name":"staging-cluster","reconcileID":"489fbe7f-5943-4f9d-8c90-7315dc7dcacd","uuid":"7c6810e5-a962-11ee-95b1-0a1a8ddfb0bf","backup":{"name":"staging-1704195093"},"backupPhase":"started"}
{"level":"info","ts":"2024-01-02T11:31:35Z","msg":"no orphan PVCs found, skipping the restored cluster reconciliation","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"staging-cluster","namespace":"..."},"namespace":"...","name":"staging-cluster","reconcileID":"04c04fe0-88a6-4e24-add7-be7b8e3dc90a","uuid":"7c998ddb-a962-11ee-95b1-0a1a8ddfb0bf"}
{"level":"info","ts":"2024-01-02T11:31:35Z","msg":"refusing to create the primary instance while the latest generated serial is not zero","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"staging-cluster","namespace":"..."},"namespace":"...","name":"staging-cluster","reconcileID":"e5d75928-215b-4e88-8e83-0991c951d6a5","uuid":"7ca2180d-a962-11ee-95b1-0a1a8ddfb0bf","latestGeneratedNode":1}
{"level":"info","ts":"2024-01-02T11:31:35Z","msg":"refusing to create the primary instance while the latest generated serial is not zero","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"staging-cluster","namespace":"..."},"namespace":"...","name":"staging-cluster","reconcileID":"cab44c31-f45a-449c-91dc-8b72c958e7b0","uuid":"7ca6b07a-a962-11ee-95b1-0a1a8ddfb0bf","latestGeneratedNode":1}
[... same message repeated every second ...]
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by YanniHu1996**
Fix bootstrapping error loop by ensuring recovery backups/snapshots
readiness before Cluster construction starts.

This patch addresses an issue where Clusters bootstrapping from
recovery could enter an error loop if the backups or snapshots were
not prepared at the time of cluster creation. It modifies the
bootstrapping process to delay the construction of the first instance
until the necessary recovery backups or snapshots are fully ready,
thus preventing the error loop.

Closes #3654

### CODE REVIEW

**Review by litaocdl — APPROVED** [review]

File: controllers/cluster_create.go [hunk 1]
```diff
@@ -968,39 +968,28 @@ func (r *ClusterReconciler) createPrimaryInstance(
...
 	var backup *apiv1.Backup
 	if cluster.Spec.Bootstrap != nil &&
-		cluster.Spec.Bootstrap.Recovery != nil &&
-		cluster.Spec.Bootstrap.Recovery.Backup != nil {
+		cluster.Spec.Bootstrap.Recovery != nil {
+		var err error
 		backup, err = r.getOriginBackup(ctx, cluster)
 		if err != nil {
 			return ctrl.Result{}, err
 		}
```
Comment (jsilvela) [inline controllers/cluster_create.go:978]: this is already there before your PR, but the flow is very confusing.
We look for a backup object in the bootstrap.recovery, and it looks like we depend on it.
But further down we may still proceed if we had boostrap.recovery.volumesnapshots.
I'm going to try to make this more explicit.

**Review by jsilvela — APPROVED** [review]

**Comment by jsilvela** [comment]
CICD run: https://github.com/EnterpriseDB/cloudnative-pg/actions/runs/7646975080

**Review by mnencia — APPROVED** [review]
