### PR TITLE
fix: update the backup status in case of errors

### LINKED ISSUE #1535: backup_controller should update the backup status in case of errors
Example: https://github.com/cloudnative-pg/cloudnative-pg/blob/8d025bc733320924f3863d7b9aee394e6d0bc7dd/controllers/backup_controller.go#L117

There are multiple cases where we change the backup status without then committing the changes to the API server.

We should proceed to update the resource after modifying it

### PR DESCRIPTION
**Pull request by armru**
This patch ensure that each time when the backup encountered some error, the failed status
and reason are committed to the api server before next reconcile loop.

Closes #1535

### CODE REVIEW

**Comment by armru** [comment]
Please note that this PR requires #1531 to be merged first

File: controllers/backup_controller.go [hunk 1]
```diff
@@ -126,6 +122,7 @@ func (r *BackupReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctr
 			clusterName)
 		contextLogger.Warning(message)
 		r.Recorder.Event(&backup, "Warning", "ClusterHasNoBackupConfig", message)
+		tryFlagBackupAsFailed(ctx, r.Client, &backup, errors.New(message))
```
Comment (mnencia) [inline controllers/backup_controller.go:125]: This conflicts with the RequeueAfter: the failed status is final and will never be reconciled again.

File: controllers/backup_controller.go [hunk 2]
```diff
@@ -200,6 +197,8 @@ func (r *BackupReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctr
 		r.Recorder.Eventf(&backup, "Warning", "Error", "Backup exit with error %v", err)
 	}
 
+	contextLogger.Debug(fmt.Sprintf("object %#q has been reconciled", req.NamespacedName))
+
```
Comment (mnencia) [inline controllers/backup_controller.go:201]: I would add `err` to the log. It could be != nil

File: controllers/backup_controller.go [hunk 3]
```diff
@@ -142,7 +139,7 @@ func (r *BackupReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctr
 			backup.Status.Phase = apiv1.BackupPhasePending
 			return ctrl.Result{RequeueAfter: 30 * time.Second}, r.Status().Update(ctx, &backup)
 		}
-		backup.Status.SetAsFailed(fmt.Errorf("while getting pod: %w", err))
+		tryFlagBackupAsFailed(ctx, r.Client, &backup, fmt.Errorf("while getting pod: %w", err))
 		r.Recorder.Eventf(&backup, "Warning", "FindingPod", "Error getting target pod: %s",
 			cluster.Status.TargetPrimary)
 		return ctrl.Result{}, r.Status().Update(ctx, &backup)
```
Comment (mnencia) [inline controllers/backup_controller.go:145]: I don't think returning an error here makes any sense. Since the backup is marked as failed, it will never rerun a reconciliation cycle. Better to log some meaningful message and `return ctrl.Result{}, nil`

File: controllers/backup_controller.go [hunk 4]
```diff
@@ -142,7 +142,7 @@ func (r *BackupReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctr
 		tryFlagBackupAsFailed(ctx, r.Client, &backup, fmt.Errorf("while getting pod: %w", err))
 		r.Recorder.Eventf(&backup, "Warning", "FindingPod", "Error getting target pod: %s",
 			cluster.Status.TargetPrimary)
-		return ctrl.Result{}, r.Status().Update(ctx, &backup)
+		return ctrl.Result{}, nil
```
Comment (mnencia) [inline controllers/backup_controller.go:145]: I think you miss the `r.Status().Update(ctx, &backup)` call here

Comment (armru) [reply controllers/backup_controller.go:145]: tryFlagBackupAsFailed does that

**Review by mnencia — APPROVED** [review]

**Review by litaocdl — APPROVED** [review]
