### PR TITLE
fix: avoid reloading ident map when not needed

### LINKED ISSUE #4626: [Bug]: each times PostgreSQL starts, we SIGHUP it two times to change the pg_ident file
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Contact Details

leonardo.cecchi@enteprisedb.com

### Version

1.23.1

### What version of Kubernetes are you using?

1.30 (unsupported)

### What is your Kubernetes environment?

Self-managed: kind (evaluation)

### How did you install the operator?

YAML manifest

### What happened?

Everytime the instance manager starts PostgreSQL, it will SIGHUP it two times to install two slightly different versions of the pg_ident file.
This is easily reproducible by fencing on and off an instance.

### Cluster resource

_No response_

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by leonardoce**
Before this patch, the instance manager could write the ident map using two different formats even if the content was semantically the same.

This was triggering an unneeded configuration reload after the postmaster was started up.

Fixes: #4626

### CODE REVIEW

File: pkg/management/postgres/restore.go [hunk 1]
```diff
@@ -715,36 +715,36 @@ func (info InitInfo) WriteInitialPostgresqlConf(cluster *apiv1.Cluster) error {
...
 	if err != nil {
-		return fmt.Errorf("while reading configuration files from ConfigMap: %w", err)
+		return fmt.Errorf("while generating pg_hba.conf: %w", err)
 	}
-	_, err = temporaryInstance.RefreshPGIdent(cluster)
+	_, err = temporaryInstance.RefreshPGIdent(cluster.Spec.PostgresConfiguration.PgIdent)
 	if err != nil {
-		return fmt.Errorf("while reading configuration files from ConfigMap: %w", err)
+		return fmt.Errorf("while generating pg_ident.conf: %w", err)
 	}
```
Comment (mnencia) [inline pkg/management/postgres/restore.go:723]: This makes no sense; we generate these files, and then we don't install them.

We should either stop generating the pg_hba.conf and pg_ident.conf here or install them.

This deserves a separate issue.

**Review by mnencia — APPROVED** [review]

File: pkg/management/postgres/configuration.go [hunk 2]
```diff
@@ -198,16 +198,22 @@ func quoteHbaLiteral(literal string) string {
...
+	)
 }
 
-// RefreshPGIdent generates and writes down the pg_ident.conf file
-func (instance *Instance) RefreshPGIdent(cluster *apiv1.Cluster) (postgresIdentChanged bool, err error) {
+// RefreshPGIdent generates and writes down the pg_ident.conf file given
+// a set of additional pg_ident lines that is usually taken from the
+// Cluster configuration
+func (instance *Instance) RefreshPGIdent(additionalLines []string) (postgresIdentChanged bool, err error) {
 	// Generate pg_hba.conf file
```
Comment (jsilvela) [inline pkg/management/postgres/configuration.go:215]:
```suggestion
	// Generate pg_ident.conf file
```

**Review by jsilvela — APPROVED** [review]

File: pkg/management/postgres/restore.go (hunk 1 above)
Comment (leonardoce) [reply pkg/management/postgres/restore.go:723]: Could you create it @mnencia ?

**Comment by leonardoce** [comment]
E2e https://github.com/EnterpriseDB/cloudnative-pg/actions/runs/9266533929
