### PR TITLE
fix: enable CSV logpipe inside WithActiveInstance function

### LINKED ISSUE #130: CSV log pipe is not started by jobs
When PostgreSQL is started by the [WithActiveInstance function](https://github.com/cloudnative-pg/cloudnative-pg/blob/476f5a1185260a35e5080fbab226f371bb398c7f/pkg/management/postgres/instance.go#L445), the log pipe that is handling the logging collector CSV output is not started.

As a result, any problem during Postgres execution is not logged to stdout and collected. This can happen, for example, with a failure during a bootstrap recovery job.

### PR DESCRIPTION
**Pull request by armru**
This patch ensures that we can collect the Postgres log files when we start the instance with the WithActiveInstance function.

It does that by starting a CSV logpipe process with the instance and terminating it before terminating the WithActiveInstance function.

Closes #130

Signed-off-by: Armando Ruocco <armando.ruocco@enterprisedb.com>

### CODE REVIEW

**Review by mnencia — APPROVED** [review]

File: pkg/management/postgres/instance.go [hunk 1]
```diff
@@ -447,10 +449,22 @@ func (instance Instance) WithActiveInstance(inner func() error) error {
 	if err != nil {
 		return fmt.Errorf("while activating instance: %w", err)
 	}
+
+	ctx, ctxCancel := context.WithCancel(context.Background())
+	csvPipe := logpipe.NewLogPipe()
```
Comment (gbartolini) [inline pkg/management/postgres/instance.go:454]:
```suggestion
	# Start the CSV logpipe to redirect log to stdout
	ctx, ctxCancel := context.WithCancel(context.Background())
	csvPipe := logpipe.NewLogPipe()
```

File: pkg/management/postgres/instance.go [hunk 2]
```diff
@@ -447,10 +449,22 @@ func (instance Instance) WithActiveInstance(inner func() error) error {
...
+
+	go func() {
+		if err := csvPipe.Start(ctx); err != nil {
```
Comment (phisco) [inline pkg/management/postgres/instance.go:458]: this will always fail when WithActiveInstance is called from CompleteCrashRecovery, but that's not a real issue.

**Review by phisco — DISMISSED** [review]

File: pkg/management/postgres/instance.go (hunk 2 above)
Comment (phisco) [reply pkg/management/postgres/instance.go:458]: Actually this could be an issue as log pipes don't know whether they are already running or not, so multiple goroutines could be spawned and attached to the same file. Given the current usages of WithActiveInstance this should never happen afaict, but it could happen in the future if the code is changed.

**Review by phisco — APPROVED** [review]
