### PR TITLE
fix: avoid reloading Postgres when unnecessary

### LINKED ISSUE #4529: [Bug]: Triggering SIGHUP too many times
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Contact Details

_No response_

### Version

1.23.0

### What version of Kubernetes are you using?

1.30 (unsuppprted)

### What is your Kubernetes environment?

Self-managed: kind (evaluation)

### How did you install the operator?

YAML manifest

### What happened?

Currently when triggering a failover or switch over in the e2e tests we can see a lot of SIGHUP like this one 
```
{"level":"info","ts":"2024-05-14T10:19:23Z","logger":"postgres","msg":"record","logging_pod":"cluster-fast-failover-3","record":{"log_time":"2024-05-14 10:19:23.300 UTC","process_id":"20","session_id":"66433aaa.14","session_line_num":"7","session_start_time":"2024-05-14 10:19:22 UTC","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"received SIGHUP, reloading configuration files","backend_type":"postmaster","query_id":"0"}}
{"level":"info","ts":"2024-05-14T10:19:23Z","logger":"postgres","msg":"record","logging_pod":"cluster-fast-failover-3","record":{"log_time":"2024-05-14 10:19:23.355 UTC","process_id":"20","session_id":"66433aaa.14","session_line_num":"8","session_start_time":"2024-05-14 10:19:22 UTC","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"received SIGHUP, reloading configuration files","backend_type":"postmaster","query_id":"0"}}
{"level":"info","ts":"2024-05-14T10:19:32Z","logger":"postgres","msg":"record","logging_pod":"cluster-fast-failover-3","record":{"log_time":"2024-05-14 10:19:32.235 UTC","process_id":"20","session_id":"66433aaa.14","session_line_num":"9","session_start_time":"2024-05-14 10:19:22 UTC","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"received SIGHUP, reloading configuration files","backend_type":"postmaster","query_id":"0"}}
{"level":"info","ts":"2024-05-14T10:19:32Z","logger":"postgres","msg":"record","logging_pod":"cluster-fast-failover-3","record":{"log_time":"2024-05-14 10:19:32.421 UTC","process_id":"20","session_id":"66433aaa.14","session_line_num":"10","session_start_time":"2024-05-14 10:19:22 UTC","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"received SIGHUP, reloading configuration files","backend_type":"postmaster","query_id":"0"}}
{"level":"info","ts":"2024-05-14T10:19:37Z","logger":"postgres","msg":"record","logging_pod":"cluster-fast-failover-3","record":{"log_time":"2024-05-14 10:19:37.348 UTC","process_id":"20","session_id":"66433aaa.14","session_line_num":"11","session_start_time":"2024-05-14 10:19:22 UTC","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"received SIGHUP, reloading configuration files","backend_type":"postmaster","query_id":"0"}}
{"level":"info","ts":"2024-05-14T10:19:37Z","logger":"postgres","msg":"record","logging_pod":"cluster-fast-failover-3","record":{"log_time":"2024-05-14 10:19:37.410 UTC","process_id":"20","session_id":"66433aaa.14","session_line_num":"12","session_start_time":"2024-05-14 10:19:22 UTC","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"received SIGHUP, reloading configuration files","backend_type":"postmaster","query_id":"0"}}
{"level":"info","ts":"2024-05-14T10:19:37Z","logger":"postgres","msg":"record","logging_pod":"cluster-fast-failover-3","record":{"log_time":"2024-05-14 10:19:37.482 UTC","process_id":"20","session_id":"66433aaa.14","session_line_num":"13","session_start_time":"2024-05-14 10:19:22 UTC","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"received SIGHUP, reloading configuration files","backend_type":"postmaster","query_id":"0"}}
{"level":"info","ts":"2024-05-14T10:19:37Z","logger":"postgres","msg":"record","logging_pod":"cluster-fast-failover-3","record":{"log_time":"2024-05-14 10:19:37.587 UTC","process_id":"20","session_id":"66433aaa.14","session_line_num":"14","session_start_time":"2024-05-14 10:19:22 UTC","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"received SIGHUP, reloading configuration files","backend_type":"postmaster","query_id":"0"}}
{"level":"info","ts":"2024-05-14T10:19:37Z","logger":"postgres","msg":"record","logging_pod":"cluster-fast-failover-3","record":{"log_time":"2024-05-14 10:19:37.646 UTC","process_id":"20","session_id":"66433aaa.14","session_line_num":"15","session_start_time":"2024-05-14 10:19:22 UTC","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"received SIGHUP, reloading configuration files","backend_type":"postmaster","query_id":"0"}}
{"level":"info","ts":"2024-05-14T10:19:38Z","logger":"postgres","msg":"record","logging_pod":"cluster-fast-failover-3","record":{"log_time":"2024-05-14 10:19:38.227 UTC","process_id":"20","session_id":"66433aaa.14","session_line_num":"16","session_start_time":"2024-05-14 10:19:22 UTC","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"received SIGHUP, reloading configuration files","backend_type":"postmaster","query_id":"0"}}
{"level":"info","ts":"2024-05-14T10:19:38Z","logger":"postgres","msg":"record","logging_pod":"cluster-fast-failover-3","record":{"log_time":"2024-05-14 10:19:38.278 UTC","process_id":"20","session_id":"66433aaa.14","session_line_num":"17","session_start_time":"2024-05-14 10:19:22 UTC","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"received SIGHUP, reloading configuration files","backend_type":"postmaster","query_id":"0"}}
{"level":"info","ts":"2024-05-14T10:19:38Z","logger":"postgres","msg":"record","logging_pod":"cluster-fast-failover-3","record":{"log_time":"2024-05-14 10:19:38.336 UTC","process_id":"20","session_id":"66433aaa.14","session_line_num":"18","session_start_time":"2024-05-14 10:19:22 UTC","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"received SIGHUP, reloading configuration files","backend_type":"postmaster","query_id":"0"}}
{"level":"info","ts":"2024-05-14T10:19:38Z","logger":"postgres","msg":"record","logging_pod":"cluster-fast-failover-3","record":{"log_time":"2024-05-14 10:19:38.399 UTC","process_id":"20","session_id":"66433aaa.14","session_line_num":"19","session_start_time":"2024-05-14 10:19:22 UTC","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"received SIGHUP, reloading configuration files","backend_type":"postmaster","query_id":"0"}}
{"level":"info","ts":"2024-05-14T10:19:38Z","logger":"postgres","msg":"record","logging_pod":"cluster-fast-failover-3","record":{"log_time":"2024-05-14 10:19:38.452 UTC","process_id":"20","session_id":"66433aaa.14","session_line_num":"20","session_start_time":"2024-05-14 10:19:22 UTC","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"received SIGHUP, reloading configuration files","backend_type":"postmaster","query_id":"0"}}
{"level":"info","ts":"2024-05-14T10:19:38Z","logger":"postgres","msg":"record","logging_pod":"cluster-fast-failover-3","record":{"log_time":"2024-05-14 10:19:38.652 UTC","process_id":"20","session_id":"66433aaa.14","session_line_num":"21","session_start_time":"2024-05-14 10:19:22 UTC","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"received SIGHUP, reloading configuration files","backend_type":"postmaster","query_id":"0"}}
{"level":"info","ts":"2024-05-14T10:19:38Z","logger":"postgres","msg":"record","logging_pod":"cluster-fast-failover-3","record":{"log_time":"2024-05-14 10:19:38.817 UTC","process_id":"20","session_id":"66433aaa.14","session_line_num":"22","session_start_time":"2024-05-14 10:19:22 UTC","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"received SIGHUP, reloading configuration files","backend_type":"postmaster","query_id":"0"}}
{"level":"info","ts":"2024-05-14T10:19:39Z","logger":"postgres","msg":"record","logging_pod":"cluster-fast-failover-3","record":{"log_time":"2024-05-14 10:19:39.350 UTC","process_id":"20","session_id":"66433aaa.14","session_line_num":"23","session_start_time":"2024-05-14 10:19:22 UTC","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"received SIGHUP, reloading configuration files","backend_type":"postmaster","query_id":"0"}}
{"level":"info","ts":"2024-05-14T10:19:47Z","logger":"postgres","msg":"record","logging_pod":"cluster-fast-failover-3","record":{"log_time":"2024-05-14 10:19:47.714 UTC","process_id":"20","session_id":"66433aaa.14","session_line_num":"24","session_start_time":"2024-05-14 10:19:22 UTC","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"received SIGHUP, reloading configuration files","backend_type":"postmaster","query_id":"0"}}
{"level":"info","ts":"2024-05-14T10:19:47Z","logger":"postgres","msg":"record","logging_pod":"cluster-fast-failover-3","record":{"log_time":"2024-05-14 10:19:47.937 UTC","process_id":"20","session_id":"66433aaa.14","session_line_num":"25","session_start_time":"2024-05-14 10:19:22 UTC","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"received SIGHUP, reloading configuration files","backend_type":"postmaster","query_id":"0"}}
{"level":"info","ts":"2024-05-14T10:19:55Z","logger":"postgres","msg":"record","logging_pod":"cluster-fast-failover-3","record":{"log_time":"2024-05-14 10:19:55.842 UTC","process_id":"20","session_id":"66433aaa.14","session_line_num":"26","session_start_time":"2024-05-14 10:19:22 UTC","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"received SIGHUP, reloading configuration files","backend_type":"postmaster","query_id":"0"}}
{"level":"info","ts":"2024-05-14T10:19:55Z","logger":"postgres","msg":"record","logging_pod":"cluster-fast-failover-3","record":{"log_time":"2024-05-14 10:19:55.946 UTC","process_id":"20","session_id":"66433aaa.14","session_line_num":"27","session_start_time":"2024-05-14 10:19:22 UTC","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"received SIGHUP, reloading configuration files","backend_type":"postmaster","query_id":"0"}}
```
And also that the server was signaled like this:
```
{"level":"info","ts":"2024-05-14T10:19:23Z","logger":"pg_ctl","msg":"server signaled","pipe":"stdout","logging_pod":"cluster-fast-failover-3"}
{"level":"info","ts":"2024-05-14T10:19:23Z","logger":"pg_ctl","msg":"server signaled","pipe":"stdout","logging_pod":"cluster-fast-failover-3"}
{"level":"info","ts":"2024-05-14T10:19:32Z","logger":"pg_ctl","msg":"server signaled","pipe":"stdout","logging_pod":"cluster-fast-failover-3"}
{"level":"info","ts":"2024-05-14T10:19:32Z","logger":"pg_ctl","msg":"server signaled","pipe":"stdout","logging_pod":"cluster-fast-failover-3"}
{"level":"info","ts":"2024-05-14T10:19:37Z","logger":"pg_ctl","msg":"server signaled","pipe":"stdout","logging_pod":"cluster-fast-failover-3"}
{"level":"info","ts":"2024-05-14T10:19:37Z","logger":"pg_ctl","msg":"server signaled","pipe":"stdout","logging_pod":"cluster-fast-failover-3"}
{"level":"info","ts":"2024-05-14T10:19:37Z","logger":"pg_ctl","msg":"server signaled","pipe":"stdout","logging_pod":"cluster-fast-failover-3"}
{"level":"info","ts":"2024-05-14T10:19:37Z","logger":"pg_ctl","msg":"server signaled","pipe":"stdout","logging_pod":"cluster-fast-failover-3"}
{"level":"info","ts":"2024-05-14T10:19:37Z","logger":"pg_ctl","msg":"server signaled","pipe":"stdout","logging_pod":"cluster-fast-failover-3"}
{"level":"info","ts":"2024-05-14T10:19:38Z","logger":"pg_ctl","msg":"server signaled","pipe":"stdout","logging_pod":"cluster-fast-failover-3"}
{"level":"info","ts":"2024-05-14T10:19:38Z","logger":"pg_ctl","msg":"server signaled","pipe":"stdout","logging_pod":"cluster-fast-failover-3"}
{"level":"info","ts":"2024-05-14T10:19:38Z","logger":"pg_ctl","msg":"server signaled","pipe":"stdout","logging_pod":"cluster-fast-failover-3"}
{"level":"info","ts":"2024-05-14T10:19:38Z","logger":"pg_ctl","msg":"server signaled","pipe":"stdout","logging_pod":"cluster-fast-failover-3"}
{"level":"info","ts":"2024-05-14T10:19:38Z","logger":"pg_ctl","msg":"server signaled","pipe":"stdout","logging_pod":"cluster-fast-failover-3"}
{"level":"info","ts":"2024-05-14T10:19:38Z","logger":"pg_ctl","msg":"server signaled","pipe":"stdout","logging_pod":"cluster-fast-failover-3"}
{"level":"info","ts":"2024-05-14T10:19:38Z","logger":"pg_ctl","msg":"server signaled","pipe":"stdout","logging_pod":"cluster-fast-failover-3"}
{"level":"info","ts":"2024-05-14T10:19:39Z","logger":"pg_ctl","msg":"server signaled","pipe":"stdout","logging_pod":"cluster-fast-failover-3"}
{"level":"info","ts":"2024-05-14T10:19:47Z","logger":"pg_ctl","msg":"server signaled","pipe":"stdout","logging_pod":"cluster-fast-failover-3"}
{"level":"info","ts":"2024-05-14T10:19:47Z","logger":"pg_ctl","msg":"server signaled","pipe":"stdout","logging_pod":"cluster-fast-failover-3"}
{"level":"info","ts":"2024-05-14T10:19:55Z","logger":"pg_ctl","msg":"server signaled","pipe":"stdout","logging_pod":"cluster-fast-failover-3"}
{"level":"info","ts":"2024-05-14T10:19:55Z","logger":"pg_ctl","msg":"server signaled","pipe":"stdout","logging_pod":"cluster-fast-failover-3"}
```
Meaning that it's us triggering the reload because we actually can see this too
```
{"level":"info","ts":"2024-05-14T10:19:23Z","msg":"reloading the instance","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-fast-failover","namespace":"primary-failover-time-async"},"namespace":"primary-failover-time-async","name":"cluster-fast-failover","reconcileID":"fb38673b-ac30-4f05-8818-2066813a0cd7","logging_pod":"cluster-fast-failover-3"}
{"level":"info","ts":"2024-05-14T10:19:23Z","msg":"Requesting configuration reload","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-fast-failover","namespace":"primary-failover-time-async"},"namespace":"primary-failover-time-async","name":"cluster-fast-failover","reconcileID":"fb38673b-ac30-4f05-8818-2066813a0cd7","logging_pod":"cluster-fast-failover-3","pgdata":"/var/lib/postgresql/data/pgdata"}
{"level":"info","ts":"2024-05-14T10:19:23Z","logger":"postgres","msg":"record","logging_pod":"cluster-fast-failover-3","record":{"log_time":"2024-05-14 10:19:23.300 UTC","process_id":"20","session_id":"66433aaa.14","session_line_num":"7","session_start_time":"2024-05-14 10:19:22 UTC","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"received SIGHUP, reloading configuration files","backend_type":"postmaster","query_id":"0"}}
{"level":"info","ts":"2024-05-14T10:19:23Z","msg":"reloading the instance","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-fast-failover","namespace":"primary-failover-time-async"},"namespace":"primary-failover-time-async","name":"cluster-fast-failover","reconcileID":"faf1109b-4ab9-4ae7-962d-97ed52e0bf75","logging_pod":"cluster-fast-failover-3"}
{"level":"info","ts":"2024-05-14T10:19:23Z","msg":"Requesting configuration reload","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-fast-failover","namespace":"primary-failover-time-async"},"namespace":"primary-failover-time-async","name":"cluster-fast-failover","reconcileID":"faf1109b-4ab9-4ae7-962d-97ed52e0bf75","logging_pod":"cluster-fast-failover-3","pgdata":"/var/lib/postgresql/data/pgdata"}
{"level":"info","ts":"2024-05-14T10:19:23Z","logger":"postgres","msg":"record","logging_pod":"cluster-fast-failover-3","record":{"log_time":"2024-05-14 10:19:23.355 UTC","process_id":"20","session_id":"66433aaa.14","session_line_num":"8","session_start_time":"2024-05-14 10:19:22 UTC","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"received SIGHUP, reloading configuration files","backend_type":"postmaster","query_id":"0"}}
{"level":"info","ts":"2024-05-14T10:19:32Z","msg":"reloading the instance","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-fast-failover","namespace":"primary-failover-time-async"},"namespace":"primary-failover-time-async","name":"cluster-fast-failover","reconcileID":"bf13c133-c6a2-4431-a8c3-762004234773","logging_pod":"cluster-fast-failover-3"}
{"level":"info","ts":"2024-05-14T10:19:32Z","msg":"Requesting configuration reload","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-fast-failover","namespace":"primary-failover-time-async"},"namespace":"primary-failover-time-async","name":"cluster-fast-failover","reconcileID":"bf13c133-c6a2-4431-a8c3-762004234773","logging_pod":"cluster-fast-failover-3","pgdata":"/var/lib/postgresql/data/pgdata"}
{"level":"info","ts":"2024-05-14T10:19:32Z","logger":"postgres","msg":"record","logging_pod":"cluster-fast-failover-3","record":{"log_time":"2024-05-14 10:19:32.235 UTC","process_id":"20","session_id":"66433aaa.14","session_line_num":"9","session_start_time":"2024-05-14 10:19:22 UTC","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"received SIGHUP, reloading configuration files","backend_type":"postmaster","query_id":"0"}}
{"level":"info","ts":"2024-05-14T10:19:32Z","msg":"reloading the instance","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-fast-failover","namespace":"primary-failover-time-async"},"namespace":"primary-failover-time-async","name":"cluster-fast-failover","reconcileID":"a337d35f-1ace-40dc-b061-17310cb2ff86","logging_pod":"cluster-fast-failover-3"}
{"level":"info","ts":"2024-05-14T10:19:32Z","msg":"Requesting configuration reload","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-fast-failover","namespace":"primary-failover-time-async"},"namespace":"primary-failover-time-async","name":"cluster-fast-failover","reconcileID":"a337d35f-1ace-40dc-b061-17310cb2ff86","logging_pod":"cluster-fast-failover-3","pgdata":"/var/lib/postgresql/data/pgdata"}
{"level":"info","ts":"2024-05-14T10:19:32Z","logger":"postgres","msg":"record","logging_pod":"cluster-fast-failover-3","record":{"log_time":"2024-05-14 10:19:32.421 UTC","process_id":"20","session_id":"66433aaa.14","session_line_num":"10","session_start_time":"2024-05-14 10:19:22 UTC","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"received SIGHUP, reloading configuration files","backend_type":"postmaster","query_id":"0"}}
{"level":"info","ts":"2024-05-14T10:19:37Z","msg":"reloading the instance","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-fast-failover","namespace":"primary-failover-time-async"},"namespace":"primary-failover-time-async","name":"cluster-fast-failover","reconcileID":"6ac0e3b1-458d-4f7c-98dc-5f9d32246ed1","logging_pod":"cluster-fast-failover-3"}
{"level":"info","ts":"2024-05-14T10:19:37Z","msg":"Requesting configuration reload","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-fast-failover","namespace":"primary-failover-time-async"},"namespace":"primary-failover-time-async","name":"cluster-fast-failover","reconcileID":"6ac0e3b1-458d-4f7c-98dc-5f9d32246ed1","logging_pod":"cluster-fast-failover-3","pgdata":"/var/lib/postgresql/data/pgdata"}
{"level":"info","ts":"2024-05-14T10:19:37Z","logger":"postgres","msg":"record","logging_pod":"cluster-fast-failover-3","record":{"log_time":"2024-05-14 10:19:37.348 UTC","process_id":"20","session_id":"66433aaa.14","session_line_num":"11","session_start_time":"2024-05-14 10:19:22 UTC","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"received SIGHUP, reloading configuration files","backend_type":"postmaster","query_id":"0"}}
{"level":"info","ts":"2024-05-14T10:19:37Z","msg":"reloading the instance","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-fast-failover","namespace":"primary-failover-time-async"},"namespace":"primary-failover-time-async","name":"cluster-fast-failover","reconcileID":"7b7c36a6-7f43-4485-a0b3-169a6307f520","logging_pod":"cluster-fast-failover-3"}
{"level":"info","ts":"2024-05-14T10:19:37Z","msg":"Requesting configuration reload","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-fast-failover","namespace":"primary-failover-time-async"},"namespace":"primary-failover-time-async","name":"cluster-fast-failover","reconcileID":"7b7c36a6-7f43-4485-a0b3-169a6307f520","logging_pod":"cluster-fast-failover-3","pgdata":"/var/lib/postgresql/data/pgdata"}
{"level":"info","ts":"2024-05-14T10:19:37Z","logger":"postgres","msg":"record","logging_pod":"cluster-fast-failover-3","record":{"log_time":"2024-05-14 10:19:37.410 UTC","process_id":"20","session_id":"66433aaa.14","session_line_num":"12","session_start_time":"2024-05-14 10:19:22 UTC","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"received SIGHUP, reloading configuration files","backend_type":"postmaster","query_id":"0"}}
{"level":"info","ts":"2024-05-14T10:19:37Z","msg":"reloading the instance","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-fast-failover","namespace":"primary-failover-time-async"},"namespace":"primary-failover-time-async","name":"cluster-fast-failover","reconcileID":"c97de8ca-f896-4e4c-8858-bef29de850a2","logging_pod":"cluster-fast-failover-3"}
{"level":"info","ts":"2024-05-14T10:19:37Z","msg":"Requesting configuration reload","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-fast-failover","namespace":"primary-failover-time-async"},"namespace":"primary-failover-time-async","name":"cluster-fast-failover","reconcileID":"c97de8ca-f896-4e4c-8858-bef29de850a2","logging_pod":"cluster-fast-failover-3","pgdata":"/var/lib/postgresql/data/pgdata"}
{"level":"info","ts":"2024-05-14T10:19:37Z","logger":"postgres","msg":"record","logging_pod":"cluster-fast-failover-3","record":{"log_time":"2024-05-14 10:19:37.482 UTC","process_id":"20","session_id":"66433aaa.14","session_line_num":"13","session_start_time":"2024-05-14 10:19:22 UTC","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"received SIGHUP, reloading configuration files","backend_type":"postmaster","query_id":"0"}}
{"level":"info","ts":"2024-05-14T10:19:37Z","msg":"reloading the instance","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-fast-failover","namespace":"primary-failover-time-async"},"namespace":"primary-failover-time-async","name":"cluster-fast-failover","reconcileID":"958d60e8-65b6-4097-ad18-12a1acf34985","logging_pod":"cluster-fast-failover-3"}
{"level":"info","ts":"2024-05-14T10:19:37Z","msg":"Requesting configuration reload","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-fast-failover","namespace":"primary-failover-time-async"},"namespace":"primary-failover-time-async","name":"cluster-fast-failover","reconcileID":"958d60e8-65b6-4097-ad18-12a1acf34985","logging_pod":"cluster-fast-failover-3","pgdata":"/var/lib/postgresql/data/pgdata"}
{"level":"info","ts":"2024-05-14T10:19:37Z","logger":"postgres","msg":"record","logging_pod":"cluster-fast-failover-3","record":{"log_time":"2024-05-14 10:19:37.587 UTC","process_id":"20","session_id":"66433aaa.14","session_line_num":"14","session_start_time":"2024-05-14 10:19:22 UTC","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"received SIGHUP, reloading configuration files","backend_type":"postmaster","query_id":"0"}}
{"level":"info","ts":"2024-05-14T10:19:37Z","msg":"reloading the instance","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-fast-failover","namespace":"primary-failover-time-async"},"namespace":"primary-failover-time-async","name":"cluster-fast-failover","reconcileID":"c7d9fc8d-d959-4813-ac6d-9180578a49d5","logging_pod":"cluster-fast-failover-3"}
{"level":"info","ts":"2024-05-14T10:19:37Z","msg":"Requesting configuration reload","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-fast-failover","namespace":"primary-failover-time-async"},"namespace":"primary-failover-time-async","name":"cluster-fast-failover","reconcileID":"c7d9fc8d-d959-4813-ac6d-9180578a49d5","logging_pod":"cluster-fast-failover-3","pgdata":"/var/lib/postgresql/data/pgdata"}
{"level":"info","ts":"2024-05-14T10:19:37Z","logger":"postgres","msg":"record","logging_pod":"cluster-fast-failover-3","record":{"log_time":"2024-05-14 10:19:37.646 UTC","process_id":"20","session_id":"66433aaa.14","session_line_num":"15","session_start_time":"2024-05-14 10:19:22 UTC","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"received SIGHUP, reloading configuration files","backend_type":"postmaster","query_id":"0"}}
{"level":"info","ts":"2024-05-14T10:19:38Z","msg":"reloading the instance","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-fast-failover","namespace":"primary-failover-time-async"},"namespace":"primary-failover-time-async","name":"cluster-fast-failover","reconcileID":"93161834-16f2-458a-ac9c-c91af6a1aaa6","logging_pod":"cluster-fast-failover-3"}
{"level":"info","ts":"2024-05-14T10:19:38Z","msg":"Requesting configuration reload","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-fast-failover","namespace":"primary-failover-time-async"},"namespace":"primary-failover-time-async","name":"cluster-fast-failover","reconcileID":"93161834-16f2-458a-ac9c-c91af6a1aaa6","logging_pod":"cluster-fast-failover-3","pgdata":"/var/lib/postgresql/data/pgdata"}
{"level":"info","ts":"2024-05-14T10:19:38Z","logger":"postgres","msg":"record","logging_pod":"cluster-fast-failover-3","record":{"log_time":"2024-05-14 10:19:38.227 UTC","process_id":"20","session_id":"66433aaa.14","session_line_num":"16","session_start_time":"2024-05-14 10:19:22 UTC","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"received SIGHUP, reloading configuration files","backend_type":"postmaster","query_id":"0"}}
{"level":"info","ts":"2024-05-14T10:19:38Z","msg":"reloading the instance","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-fast-failover","namespace":"primary-failover-time-async"},"namespace":"primary-failover-time-async","name":"cluster-fast-failover","reconcileID":"46a981e8-862c-4b7e-8287-2e909be39808","logging_pod":"cluster-fast-failover-3"}
{"level":"info","ts":"2024-05-14T10:19:38Z","msg":"Requesting configuration reload","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-fast-failover","namespace":"primary-failover-time-async"},"namespace":"primary-failover-time-async","name":"cluster-fast-failover","reconcileID":"46a981e8-862c-4b7e-8287-2e909be39808","logging_pod":"cluster-fast-failover-3","pgdata":"/var/lib/postgresql/data/pgdata"}
{"level":"info","ts":"2024-05-14T10:19:38Z","logger":"postgres","msg":"record","logging_pod":"cluster-fast-failover-3","record":{"log_time":"2024-05-14 10:19:38.278 UTC","process_id":"20","session_id":"66433aaa.14","session_line_num":"17","session_start_time":"2024-05-14 10:19:22 UTC","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"received SIGHUP, reloading configuration files","backend_type":"postmaster","query_id":"0"}}
{"level":"info","ts":"2024-05-14T10:19:38Z","msg":"reloading the instance","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-fast-failover","namespace":"primary-failover-time-async"},"namespace":"primary-failover-time-async","name":"cluster-fast-failover","reconcileID":"f2944285-0dbf-4858-83a8-7d5bb94c04b0","logging_pod":"cluster-fast-failover-3"}
{"level":"info","ts":"2024-05-14T10:19:38Z","msg":"Requesting configuration reload","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-fast-failover","namespace":"primary-failover-time-async"},"namespace":"primary-failover-time-async","name":"cluster-fast-failover","reconcileID":"f2944285-0dbf-4858-83a8-7d5bb94c04b0","logging_pod":"cluster-fast-failover-3","pgdata":"/var/lib/postgresql/data/pgdata"}
{"level":"info","ts":"2024-05-14T10:19:38Z","logger":"postgres","msg":"record","logging_pod":"cluster-fast-failover-3","record":{"log_time":"2024-05-14 10:19:38.336 UTC","process_id":"20","session_id":"66433aaa.14","session_line_num":"18","session_start_time":"2024-05-14 10:19:22 UTC","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"received SIGHUP, reloading configuration files","backend_type":"postmaster","query_id":"0"}}
{"level":"info","ts":"2024-05-14T10:19:38Z","msg":"reloading the instance","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-fast-failover","namespace":"primary-failover-time-async"},"namespace":"primary-failover-time-async","name":"cluster-fast-failover","reconcileID":"fac134e7-3a95-4ba7-8f74-4d99b9cd173f","logging_pod":"cluster-fast-failover-3"}
{"level":"info","ts":"2024-05-14T10:19:38Z","msg":"Requesting configuration reload","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-fast-failover","namespace":"primary-failover-time-async"},"namespace":"primary-failover-time-async","name":"cluster-fast-failover","reconcileID":"fac134e7-3a95-4ba7-8f74-4d99b9cd173f","logging_pod":"cluster-fast-failover-3","pgdata":"/var/lib/postgresql/data/pgdata"}
{"level":"info","ts":"2024-05-14T10:19:38Z","logger":"postgres","msg":"record","logging_pod":"cluster-fast-failover-3","record":{"log_time":"2024-05-14 10:19:38.399 UTC","process_id":"20","session_id":"66433aaa.14","session_line_num":"19","session_start_time":"2024-05-14 10:19:22 UTC","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"received SIGHUP, reloading configuration files","backend_type":"postmaster","query_id":"0"}}
{"level":"info","ts":"2024-05-14T10:19:38Z","msg":"reloading the instance","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-fast-failover","namespace":"primary-failover-time-async"},"namespace":"primary-failover-time-async","name":"cluster-fast-failover","reconcileID":"b3a3af17-2e74-424f-a3b0-54c1a47adb06","logging_pod":"cluster-fast-failover-3"}
{"level":"info","ts":"2024-05-14T10:19:38Z","msg":"Requesting configuration reload","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-fast-failover","namespace":"primary-failover-time-async"},"namespace":"primary-failover-time-async","name":"cluster-fast-failover","reconcileID":"b3a3af17-2e74-424f-a3b0-54c1a47adb06","logging_pod":"cluster-fast-failover-3","pgdata":"/var/lib/postgresql/data/pgdata"}
{"level":"info","ts":"2024-05-14T10:19:38Z","logger":"postgres","msg":"record","logging_pod":"cluster-fast-failover-3","record":{"log_time":"2024-05-14 10:19:38.452 UTC","process_id":"20","session_id":"66433aaa.14","session_line_num":"20","session_start_time":"2024-05-14 10:19:22 UTC","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"received SIGHUP, reloading configuration files","backend_type":"postmaster","query_id":"0"}}
{"level":"info","ts":"2024-05-14T10:19:38Z","msg":"reloading the instance","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-fast-failover","namespace":"primary-failover-time-async"},"namespace":"primary-failover-time-async","name":"cluster-fast-failover","reconcileID":"abf9dd46-3e26-4729-960b-056fec463d4c","logging_pod":"cluster-fast-failover-3"}
{"level":"info","ts":"2024-05-14T10:19:38Z","msg":"Requesting configuration reload","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-fast-failover","namespace":"primary-failover-time-async"},"namespace":"primary-failover-time-async","name":"cluster-fast-failover","reconcileID":"abf9dd46-3e26-4729-960b-056fec463d4c","logging_pod":"cluster-fast-failover-3","pgdata":"/var/lib/postgresql/data/pgdata"}
{"level":"info","ts":"2024-05-14T10:19:38Z","logger":"postgres","msg":"record","logging_pod":"cluster-fast-failover-3","record":{"log_time":"2024-05-14 10:19:38.652 UTC","process_id":"20","session_id":"66433aaa.14","session_line_num":"21","session_start_time":"2024-05-14 10:19:22 UTC","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"received SIGHUP, reloading configuration files","backend_type":"postmaster","query_id":"0"}}
{"level":"info","ts":"2024-05-14T10:19:38Z","msg":"reloading the instance","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-fast-failover","namespace":"primary-failover-time-async"},"namespace":"primary-failover-time-async","name":"cluster-fast-failover","reconcileID":"d57646a1-6cbc-413f-a250-2b34bf99559a","logging_pod":"cluster-fast-failover-3"}
{"level":"info","ts":"2024-05-14T10:19:38Z","msg":"Requesting configuration reload","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-fast-failover","namespace":"primary-failover-time-async"},"namespace":"primary-failover-time-async","name":"cluster-fast-failover","reconcileID":"d57646a1-6cbc-413f-a250-2b34bf99559a","logging_pod":"cluster-fast-failover-3","pgdata":"/var/lib/postgresql/data/pgdata"}
{"level":"info","ts":"2024-05-14T10:19:38Z","logger":"postgres","msg":"record","logging_pod":"cluster-fast-failover-3","record":{"log_time":"2024-05-14 10:19:38.817 UTC","process_id":"20","session_id":"66433aaa.14","session_line_num":"22","session_start_time":"2024-05-14 10:19:22 UTC","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"received SIGHUP, reloading configuration files","backend_type":"postmaster","query_id":"0"}}
{"level":"info","ts":"2024-05-14T10:19:39Z","msg":"reloading the instance","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-fast-failover","namespace":"primary-failover-time-async"},"namespace":"primary-failover-time-async","name":"cluster-fast-failover","reconcileID":"2727231f-b4b4-4342-9a1e-3802716f2fe4","logging_pod":"cluster-fast-failover-3"}
{"level":"info","ts":"2024-05-14T10:19:39Z","msg":"Requesting configuration reload","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-fast-failover","namespace":"primary-failover-time-async"},"namespace":"primary-failover-time-async","name":"cluster-fast-failover","reconcileID":"2727231f-b4b4-4342-9a1e-3802716f2fe4","logging_pod":"cluster-fast-failover-3","pgdata":"/var/lib/postgresql/data/pgdata"}
{"level":"info","ts":"2024-05-14T10:19:39Z","logger":"postgres","msg":"record","logging_pod":"cluster-fast-failover-3","record":{"log_time":"2024-05-14 10:19:39.350 UTC","process_id":"20","session_id":"66433aaa.14","session_line_num":"23","session_start_time":"2024-05-14 10:19:22 UTC","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"received SIGHUP, reloading configuration files","backend_type":"postmaster","query_id":"0"}}
{"level":"info","ts":"2024-05-14T10:19:47Z","msg":"reloading the instance","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-fast-failover","namespace":"primary-failover-time-async"},"namespace":"primary-failover-time-async","name":"cluster-fast-failover","reconcileID":"954677ee-6557-4527-a8e4-60d0e2403d6a","logging_pod":"cluster-fast-failover-3"}
{"level":"info","ts":"2024-05-14T10:19:47Z","msg":"Requesting configuration reload","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-fast-failover","namespace":"primary-failover-time-async"},"namespace":"primary-failover-time-async","name":"cluster-fast-failover","reconcileID":"954677ee-6557-4527-a8e4-60d0e2403d6a","logging_pod":"cluster-fast-failover-3","pgdata":"/var/lib/postgresql/data/pgdata"}
{"level":"info","ts":"2024-05-14T10:19:47Z","logger":"postgres","msg":"record","logging_pod":"cluster-fast-failover-3","record":{"log_time":"2024-05-14 10:19:47.714 UTC","process_id":"20","session_id":"66433aaa.14","session_line_num":"24","session_start_time":"2024-05-14 10:19:22 UTC","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"received SIGHUP, reloading configuration files","backend_type":"postmaster","query_id":"0"}}
{"level":"info","ts":"2024-05-14T10:19:47Z","msg":"reloading the instance","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-fast-failover","namespace":"primary-failover-time-async"},"namespace":"primary-failover-time-async","name":"cluster-fast-failover","reconcileID":"0580ba81-288e-46c3-99b4-cf31c5fd2e50","logging_pod":"cluster-fast-failover-3"}
{"level":"info","ts":"2024-05-14T10:19:47Z","msg":"Requesting configuration reload","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-fast-failover","namespace":"primary-failover-time-async"},"namespace":"primary-failover-time-async","name":"cluster-fast-failover","reconcileID":"0580ba81-288e-46c3-99b4-cf31c5fd2e50","logging_pod":"cluster-fast-failover-3","pgdata":"/var/lib/postgresql/data/pgdata"}
{"level":"info","ts":"2024-05-14T10:19:47Z","logger":"postgres","msg":"record","logging_pod":"cluster-fast-failover-3","record":{"log_time":"2024-05-14 10:19:47.937 UTC","process_id":"20","session_id":"66433aaa.14","session_line_num":"25","session_start_time":"2024-05-14 10:19:22 UTC","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"received SIGHUP, reloading configuration files","backend_type":"postmaster","query_id":"0"}}
{"level":"info","ts":"2024-05-14T10:19:55Z","msg":"reloading the instance","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-fast-failover","namespace":"primary-failover-time-async"},"namespace":"primary-failover-time-async","name":"cluster-fast-failover","reconcileID":"c97b3698-8eea-4721-aa2f-4665e728129f","logging_pod":"cluster-fast-failover-3"}
{"level":"info","ts":"2024-05-14T10:19:55Z","msg":"Requesting configuration reload","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-fast-failover","namespace":"primary-failover-time-async"},"namespace":"primary-failover-time-async","name":"cluster-fast-failover","reconcileID":"c97b3698-8eea-4721-aa2f-4665e728129f","logging_pod":"cluster-fast-failover-3","pgdata":"/var/lib/postgresql/data/pgdata"}
{"level":"info","ts":"2024-05-14T10:19:55Z","logger":"postgres","msg":"record","logging_pod":"cluster-fast-failover-3","record":{"log_time":"2024-05-14 10:19:55.842 UTC","process_id":"20","session_id":"66433aaa.14","session_line_num":"26","session_start_time":"2024-05-14 10:19:22 UTC","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"received SIGHUP, reloading configuration files","backend_type":"postmaster","query_id":"0"}}
{"level":"info","ts":"2024-05-14T10:19:55Z","msg":"reloading the instance","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-fast-failover","namespace":"primary-failover-time-async"},"namespace":"primary-failover-time-async","name":"cluster-fast-failover","reconcileID":"8409dc9f-6e3c-4ffd-8660-3c190ec2abf5","logging_pod":"cluster-fast-failover-3"}
{"level":"info","ts":"2024-05-14T10:19:55Z","msg":"Requesting configuration reload","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-fast-failover","namespace":"primary-failover-time-async"},"namespace":"primary-failover-time-async","name":"cluster-fast-failover","reconcileID":"8409dc9f-6e3c-4ffd-8660-3c190ec2abf5","logging_pod":"cluster-fast-failover-3","pgdata":"/var/lib/postgresql/data/pgdata"}
{"level":"info","ts":"2024-05-14T10:19:55Z","logger":"postgres","msg":"record","logging_pod":"cluster-fast-failover-3","record":{"log_time":"2024-05-14 10:19:55.946 UTC","process_id":"20","session_id":"66433aaa.14","session_line_num":"27","session_start_time":"2024-05-14 10:19:22 UTC","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"received SIGHUP, reloading configuration files","backend_type":"postmaster","query_id":"0"}}
```

### Cluster resource

_No response_

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by leonardoce**
The instance manager stores the PostgreSQL configuration inside a dictionary, mapping GUC names to their actual value.

When writing the configuration file, the code is iterating over a map. Since the iteration order is not defined, the configuration file was re-written even when the parameters didn't change.

This made the instance manager SIGHUP the postmaster every time, even if this was not needed.

This patch fixes the issue by writing the configuration file in lexicographic order.

Closes: #4529

### CODE REVIEW

**Review by gbartolini — APPROVED** [review]

File: pkg/configfile/configfile.go [hunk 1]
```diff
@@ -86,18 +86,20 @@ func UpdateConfigurationContents(lines []string, options map[string]string) ([]s
...
 	}
 
 	return lines, nil
 }
 
-// WritePostgresConfigurationFile replaces the content of a Postgres configuration file
-// with the provide options
-func WritePostgresConfigurationFile(
+// WritePostgresConfiguration replaces the content of a Postgres configuration file
+// with the options provided
```
Comment (gbartolini) [inline pkg/configfile/configfile.go:101]:
```suggestion
// WritePostgresConfiguration replaces the content of a PostgreSQL configuration
// file with the provided options
```

**Review by armru — APPROVED** [review]

**Comment by leonardoce** [comment]
I'm waiting for the E2e test to finish before merging it.

**Review by mnencia — APPROVED** [review]
