### PR TITLE
fix: allow raising replication parameters when restoring a backup

### LINKED ISSUE #2478: Recovery failure with barman due to max_connections
CNPG version: 1.20.1

I'm trying to recover from a backup that was produced with barmanObjectStore but recovering the primary instance fails.
In postgresql.parameters.max_connections I use a value of 40, and because of that the following error is produced:
"message":"hot standby is not possible because of insufficient parameter settings","detail":"max_connections = 10 is a lower setting than on the primary server, where its value was 40."
Meaning that recovery from a backup must use at least as large max_connections as what was used by the backup.

Tracking down the code I figured that the max_connections=10 setting comes from pg_controldata([src](https://github.com/cloudnative-pg/cloudnative-pg/blob/c4a369fff121f4060db9c53df99bae73292b2caf/pkg/management/postgres/restore.go#L71)), which strictly overwrites the user setting.

I guess the user should be able to override max_connections when running a recovery to match that was backed up?

I've checked and /var/lib/postgresql/data/pgdata/custom.conf indeed shows max_connections=10.
What's confusing though is that running pg_controldata displays "max_connections setting: 40" so I'm confused where that 10 comes from.
The logs show this: {..., "msg":"enforcing parameters found in pg_controldata","parameters":{"max_connections":"10","max_locks_per_transaction":"64","max_prepared_transactions":"0","max_wal_senders":"10","max_worker_processes":"32"}}

### PR DESCRIPTION
**Pull request by litaocdl**
Ensure the PostgreSQL replication parameters are set to the higher value between
the ones specified in the cluster specification and the ones stored in the backup.

This will ensure that the backup will be restored correctly while allowing the users
to raise their value to accommodate changes in the configuration that have
happened after the backup was taken.

Partially closes #2478 #2337

### CODE REVIEW

**Comment by litaocdl** [comment]
e2e is running here https://github.com/EnterpriseDB/cloudnative-pg/actions/runs/9136158988

**Comment by mnencia** [comment]
E2E test running on the fork https://github.com/EnterpriseDB/cloudnative-pg/actions/runs/9251317637

**Review by mnencia — APPROVED** [review]

**Review by YanniHu1996 — APPROVED** [review]

File: pkg/management/postgres/restore.go [hunk 1]
```diff
@@ -601,22 +602,31 @@ func (info InitInfo) writeRecoveryConfiguration(recoveryFileContents string) err
 		return fmt.Errorf("cannot write recovery config: %w", err)
 	}
 
-	enforcedParams, err := GetEnforcedParametersThroughPgControldata(info.PgData)
+	controldataParams, err := LoadEnforcedParametersFromPgControldata(info.PgData)
```
Comment (leonardoce) [inline pkg/management/postgres/restore.go:605]:
```suggestion
	// Now we need to choose which parameters to use to complete the recovery
	// of this PostgreSQL instance.
	// We know the values that these parameters had when the backup was started
	// from the `pg_controldata` output.
	// We don't know how these values were set in the newer WALs.
	//
	// The only way to proceed is to rely on the user-defined configuration,
	// with the caveat of ensuring that the values are high enough to be
	// able to start recovering the backup.
	//
	// To be on the safe side, we'll use the largest setting we find
	// from `pg_controldata` and the Cluster definition.
	//
	// https://www.postgresql.org/docs/16/hot-standby.html#HOT-STANDBY-ADMIN
	controldataParams, err := LoadEnforcedParametersFromPgControldata(info.PgData)
```

File: internal/management/controller/instance_controller.go [hunk 2]
```diff
@@ -394,30 +394,25 @@ func (r *InstanceReconciler) verifyParametersForFollower(cluster *apiv1.Cluster)
...
+	}
+	clusterParams, err := postgresManagement.LoadEnforcedParametersFromCluster(cluster)
 	if err != nil {
 		return err
 	}
 
-	clusterParams := cluster.Spec.PostgresConfiguration.Parameters
 	options := make(map[string]string)
-	for key, enforcedparam := range enforcedParams {
+	for key, enforcedparam := range controldataParams {
```
Comment (leonardoce) [inline internal/management/controller/instance_controller.go:407]: Isn't this logic exactly the same as what we have here? https://github.com/cloudnative-pg/cloudnative-pg/pull/4564/files#diff-7b2e81429f27e9e75a48e70527067a4d8a80a2450dab880b4b228d501359b7a8R688

If it is, better encapsulate and use it two times.

**Review by leonardoce — CHANGES_REQUESTED** [review]

File: internal/management/controller/instance_controller.go (hunk 2 above)
Comment (litaocdl) [reply internal/management/controller/instance_controller.go:407]: The one in instance mgr, we only refresh if pgcontrol is higher than user specific, make sure the standby has a higher value.  In restore, we use the higher value between use defined and pgcontrol.

Comment (leonardoce) [reply internal/management/controller/instance_controller.go:407]: I think it is the same, as you're always going to get a value from `controldataParams[X]`, and that value will always be greater than `0`.

Comment (litaocdl) [reply internal/management/controller/instance_controller.go:407]: you are right, I misunderstood

Comment (leonardoce) [reply internal/management/controller/instance_controller.go:407]: Yep, perhaps it was better for me to file this comment against the other occurrence of that cycle.

Comment (leonardoce) [reply internal/management/controller/instance_controller.go:407]: Let's leave them as they are, refactoring it now is way too much pain for the advantage we get.

**Review by leonardoce — APPROVED** [review]

**Comment by leonardoce** [comment]
https://github.com/EnterpriseDB/cloudnative-pg/actions/runs/9315905824
