### PR TITLE
fix: version upgrade logic in patch #198

### LINKED ISSUE #329: Wrong logic to upgrade the conditions to the new format during the upgrade
The part of pull request #198 regarding the upgrade from a version setting reasons containing space is wrong because it is impossible to update the status in a defaulting webhook or with a simple Update call. Moreover, the setDefault function misses the difference because it only compares the content of the spec section.

In most cases, the current code works anyway because the Cluster reconciliation loop must update the status after an operator upgrade. However, in rare cases, it could lead to a cluster that is impossible to upgrade.

### PR DESCRIPTION
**Pull request by mnencia**
The part of pull request #198 regarding the upgrade from a version
setting reasons containing space is wrong because it is impossible to
update the status in a defaulting webhook or with a simple Update
call. Moreover, the setDefault function misses the difference because
it only compares the content of the spec section.

In most cases, the previous code works anyway because the Cluster
reconciliation loop must update the status after an operator
upgrade. However, in rare cases, it could lead to a cluster that is
impossible to upgrade.

This patch fixes the issue by moving the upgrade code from the webhook
to the main controller reconciliation loop.

Closes #329

Signed-off-by: Marco Nenciarini <marco.nenciarini@enterprisedb.com>

### CODE REVIEW

**Review by phisco — APPROVED** [review]

**Review by armru — APPROVED** [review]

File: controllers/cluster_status.go [hunk 1]
```diff
@@ -365,6 +365,24 @@ func (r *ClusterReconciler) updateResourceStatus(
...
+	conditions := make([]metav1.Condition, 0, len(cluster.Status.Conditions))
+	for _, entry := range cluster.Status.Conditions {
+		if utils.IsConditionReasonValid(entry.Reason) {
+			conditions = append(conditions, entry)
+		}
+	}
+
+	if !reflect.DeepEqual(cluster.Status.Conditions, conditions) {
+		cluster.Status.Conditions = conditions
+		return r.Status().Update(ctx, cluster)
```
Comment (Anhui-tqhuang) [inline controllers/cluster_status.go:380]: if we call this `r.Status.Update(ctx, cluster)` without finishing this reconcile, this will cause
- a new worker will pick up the update event in the work queue and proceed the cluster
- this reconcile will continue to proceed the cluster

and when they call update, one of them will fail due to the conflict
```sh
the object has been modified; please apply your changes to the latest version and try again
```
