### PR TITLE
fix: add support for PgBouncer 1.24

### LINKED ISSUE #6566: [Bug]: Error Executing SHOW STATS in PgBouncer
### Is there an existing issue already for this bug?

- [x] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [x] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [x] I have read the troubleshooting guide and I think this is a new bug.

### Contact Details

kirillov@evrone.com

### Version

1.25 (latest patch)

### What version of Kubernetes are you using?

1.29

### What is your Kubernetes environment?

Cloud: Other

### How did you install the operator?

YAML manifest

### What happened?

After updating PgBouncer to the new version (1.24.0) using the image `ghcr.io/cloudnative-pg/pgbouncer:1.24.0`, I have encountered several errors related to metrics.

```json

{"level":"error","ts":"2025-01-11T10:28:58.707682986Z","msg":"Error while executing SHOW STATS","logger":"pgbouncer-manager"
,"error":"sql: expected 23 destination arguments in Scan, not 17","stacktrace":"github.com/cloudnative-pg/machinery/pkg/log.(*logger).
Error\n\tpkg/mod/github.com/cloudnative-pg/machinery@v0.0.0-20241219102532-2807bc88310d/pkg/log/log.go:125\ngithub.com/cloudnative-pg/
cloudnative-pg/pkg/management/pgbouncer/metricsserver.(*Exporter).collectShowStats\n\tpkg/management/pgbouncer/metricsserver/stats.go:
285\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/pgbouncer/metricsserver.(*Exporter).collectPgBouncerMetrics\n\tpkg/manage
ment/pgbouncer/metricsserver/pgbouncer_collector.go:144\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/pgbouncer/metricsserv
er.(*Exporter).Collect\n\tpkg/management/pgbouncer/metricsserver/pgbouncer_collector.go:119\ngithub.com/prometheus/client_golang/prome
theus.(*Registry).Gather.func1\n\tpkg/mod/github.com/prometheus/client_golang@v1.20.5/prometheus/registry.go:456"}
```

When executing the `SHOW STATS` command in PgBouncer, an error occurs indicating a mismatch between the expected number of columns and the actual output. The error message is as follows:

```
Error while executing SHOW STATS: sql: expected 23 destination arguments in Scan, not 17
```

This suggests that the code responsible for processing the results of the `SHOW STATS` command is not aligned with the actual structure of the output.

The same issue occurs when executing the SHOW POOLS command.

#### Details
The `SHOW STATS` command currently returns a set of statistics that includes various metrics about database connections and queries. However, it appears that the implementation in the codebase at [stats.go](https://github.com/cloudnative-pg/cloudnative-pg/blob/main/pkg/management/pgbouncer/metricsserver/stats.go#L264) is expecting a different number of columns than what is being returned.

The output from the `SHOW STATS` command is as follows:

```
-[ RECORD 1 ]-----------------+----------
database                      | my_database
total_server_assignment_count | 26
total_xact_count              | 7180
total_query_count             | 7180
total_received                | 1458529
total_sent                    | 8538725
total_xact_time               | 2190046
total_query_time              | 2190046
total_wait_time               | 282832
total_client_parse_count      | 0
total_server_parse_count      | 0
total_bind_count              | 0
avg_server_assignment_count   | 0
avg_xact_count                | 0
avg_query_count               | 0
avg_recv                      | 0
avg_sent                      | 0
avg_xact_time                 | 0
avg_query_time                | 0
avg_wait_time                 | 0
avg_client_parse_count        | 0
avg_server_parse_count        | 0
avg_bind_count                | 0
```

#### Expected Behavior
The code should correctly handle and parse all columns returned by the `SHOW STATS` command without throwing an error. The discrepancy indicates that either the PgBouncer version has changed the output format or there is an oversight in the metrics server's implementation.

### Cluster resource

```shell

```

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by sxd**
The new vlersion of PgBouncer 1.24 add new metrics, following the release notes: https://github.com/pgbouncer/pgbouncer/releases/tag/pgbouncer_1_24_0 we add support for:
* total_bind_count
* total_client_parse_count
* total_server_parse_count
* avg_bind_ount
* avg_client_parse_count
* avg_server_parse_count

Closes #6566

### CODE REVIEW

File: pkg/management/pgbouncer/metricsserver/pools.go [hunk 1]
```diff
@@ -180,6 +181,12 @@ func NewShowPoolsMetrics(subsystem string) *ShowPoolsMetrics {
 			Name:      "pool_mode",
 			Help:      "The pooling mode in use. 1 for session, 2 for transaction, 3 for statement, -1 if unknown",
 		}, []string{"database", "user"}),
+		LoadBalanceHosts: prometheus.NewGaugeVec(prometheus.GaugeOpts{
+			Namespace: PrometheusNamespace,
+			Subsystem: subsystem,
+			Name:      "load_balance_hosts",
+			Help:      "Number of hosts not load balancing between hosts",
```
Comment (gabriele-wolfox) [inline pkg/management/pgbouncer/metricsserver/pools.go:188]: As the description here is correct but not so straightforward to digest, 
I would add a reference to the related PG Bouncer PR description.
https://github.com/pgbouncer/pgbouncer/pull/736#issue-1294438051 

WDYT @sxd ?

Comment (gabriele-wolfox) [inline pkg/management/pgbouncer/metricsserver/pools.go:188]:
```suggestion
			Help:      "Number of hosts not load balancing between hosts.. See https://github.com/pgbouncer/pgbouncer/pull/736#issue-1294438051 for futher details",
```

Comment (gabriele-wolfox) [reply pkg/management/pgbouncer/metricsserver/pools.go:188]: After speaking with Jonathan, I agree that we should reference that in the commit message or documentation, not in the description of the output.

**Review by gabriele-wolfox — APPROVED** [review]
LGTM

**Review by armru — APPROVED** [review]

**Review by mnencia — APPROVED** [review]
