### PR TITLE
fix: makes VolumeSnapshot CRD optional

### LINKED ISSUE #2931: Operator is failing to start when the VolumeSnapshot CRD is not available
In some Kubernetes distributions, the `VolumeSnapshot` CRD is optional and can be installed when needed.

In these cases, the operator is refusing to start with this error:

```
{
  "level": "error",
  "ts": "2023-09-28T10:12:19Z",
  "logger": "controller-runtime.source.EventHandler",
  "msg": "failed to get informer from cache",
  "error": "failed to get API group resources: unable to retrieve the complete list of server APIs: snapshot.storage.k8s.io/v1: the server could not find the requested resource",
  "stacktrace": "sigs.k8s.io/controller-runtime/pkg/internal/source.(*Kind).Start.func1.1\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/source/kind.go:68\nk8s.io/apimachinery/pkg/util/wait.loopConditionUntilContext.func1\n\tpkg/mod/k8s.io/apimachinery@v0.28.1/pkg/util/wait/loop.go:49\nk8s.io/apimachinery/pkg/util/wait.loopConditionUntilContext\n\tpkg/mod/k8s.io/apimachinery@v0.28.1/pkg/util/wait/loop.go:50\nk8s.io/apimachinery/pkg/util/wait.PollUntilContextCancel\n\tpkg/mod/k8s.io/apimachinery@v0.28.1/pkg/util/wait/poll.go:33\nsigs.k8s.io/controller-runtime/pkg/internal/source.(*Kind).Start.func1\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/source/kind.go:56"
}
```

We need to detect this error and proceed nevertheless. Obviously, VolumeSnapshots will not work.

### PR DESCRIPTION
**Pull request by leonardoce**
This patch uses the discovery API to tell whether the VolumeSnapshot CRD is installed. If it isn't, the operator will continue working correctly but VolumeSnapshots backups will error out.

Closes #2931

### CODE REVIEW

**Review by armru — APPROVED** [review]

File: controllers/backup_controller.go [hunk 1]
```diff
@@ -131,6 +135,15 @@ func (r *BackupReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctr
 		return ctrl.Result{}, nil
 	}
 
+	if backup.Spec.Method == apiv1.BackupMethodVolumeSnapshot && !utils.HaveVolumeSnapshot() {
+		message := fmt.Sprintf(
+			"cannot proceed with the backup because Kubernetes cluster have no VolumeSnapshot support")
```
Comment (gbartolini) [inline controllers/backup_controller.go:140]:
```suggestion
			"cannot proceed with the backup as the Kubernetes cluster has no VolumeSnapshot support")
```

File: internal/cmd/manager/controller/controller.go [hunk 2]
```diff
@@ -194,6 +194,12 @@ func RunController(
 		return err
 	}
 
+	// Detect if we are running under a system that implements Volume Snapshots
```
Comment (gbartolini) [inline internal/cmd/manager/controller/controller.go:197]:
```suggestion
	// Detect if we are running under a system that provides Volume Snapshots
```

**Review by gbartolini — APPROVED** [review]
