### PR TITLE
fix: `schemaOnly` import doesn't need a default value

### LINKED ISSUE #3106: Make schemaOnly value not have a default
Some the Import section has a default value that make it create a section leaving the type section with a valid value

### PR DESCRIPTION
**Pull request by sxd**
Remove the default value for `.spec.bootstrap.import.schemaOnly`
to fix the UI in the OLM Cluster creation interface.

Closes #3106

### CODE REVIEW

File: api/v1/cluster_types.go [hunk 1]
```diff
@@ -1300,14 +1300,14 @@ const (
...
+	Source ImportSource `json:"source,omitempty"`
 
 	// The import type. Can be `microservice` or `monolith`.
 	// +kubebuilder:validation:Enum=microservice;monolith
-	Type SnapshotType `json:"type"`
+	Type SnapshotType `json:"type,omitempty"`
 
 	// The databases to import
-	Databases []string `json:"databases"`
+	Databases []string `json:"databases,omitempty"`
```
Comment (mnencia) [inline api/v1/cluster_types.go:1310]: This changes need to be reverted.

**Review by mnencia — CHANGES_REQUESTED** [review]

**Review by NiccoloFei — APPROVED** [review]
