### PR TITLE
fix: replica cluster should restart after promotion

### LINKED ISSUE #4172: [Bug]: Replica cluster require a restart after promote
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Contact Details

_No response_

### Version

1.22.2

### What version of Kubernetes are you using?

1.29

### What is your Kubernetes environment?

Self-managed: kind (evaluation)

### How did you install the operator?

YAML manifest

### What happened?

when replica cluster promoted, `archive_mode` changed from always to on but primary is not restart, once scale up the cluster, primary will restart. 

### Cluster resource

_No response_

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by litaocdl**
When a replica cluster is promoted, the `archive_mode` is changed from
`always` to `on`. This change requires a restart because Postgres 
does not reload the configuration during the promotion.

Closes: #4172

### CODE REVIEW

File: internal/management/controller/instance_controller.go [hunk 1]
```diff
@@ -1114,7 +1113,7 @@ func (r *InstanceReconciler) reconcilePrimary(ctx context.Context, cluster *apiv
 		if err := r.handlePromotion(ctx, cluster); err != nil {
 			return false, err
 		}
-		restarted = true
+		promoted = true
```
Comment (jsilvela) [inline internal/management/controller/instance_controller.go:1116]: This is not your PR but the existing code.
This is asymmetric. We decide that the instance is a primary with IsPrimary, which checks for the existence of "recovery.conf"

Let's say we:
1. successfully promote the instace
2. when trying to update the Status or drop the connections, we fail

Then the next time around we'll see the instance is a primary, and we won't retry.

File: internal/management/controller/instance_controller.go [hunk 2]
```diff
@@ -171,18 +171,17 @@ func (r *InstanceReconciler) Reconcile(
 		return reconcile.Result{RequeueAfter: time.Second}, nil
 	}
 
-	restarted, err := r.reconcilePrimary(ctx, cluster)
-	if err != nil {
+	// If the instance is promoted, it will not automatically load the changed configuration files
+	// so promoted should not stop the instance reload requires
+	if _, err := r.reconcilePrimary(ctx, cluster); err != nil {
```
Comment (jsilvela) [inline internal/management/controller/instance_controller.go:176]: This seems to make sense, and the E2E are looking very green.

**Review by jsilvela — APPROVED** [review]

File: internal/management/controller/instance_controller.go [hunk 3]
```diff
@@ -171,18 +171,17 @@ func (r *InstanceReconciler) Reconcile(
 		return reconcile.Result{RequeueAfter: time.Second}, nil
 	}
 
-	restarted, err := r.reconcilePrimary(ctx, cluster)
-	if err != nil {
+	// If the instance is promoted, it will not automatically load the changed configuration files
+	// so promoted should not stop the instance reload requires
```
Comment (jsilvela) [inline internal/management/controller/instance_controller.go:175]:
```suggestion
	// Instance promotion will not automatically load the changed configuration files.
	// Therefore it should not be counted as "a restart" to prevent instance restart.
```

File: internal/management/controller/instance_controller.go [hunk 4]
```diff
@@ -171,18 +171,17 @@ func (r *InstanceReconciler) Reconcile(
 		return reconcile.Result{RequeueAfter: time.Second}, nil
 	}
 
-	restarted, err := r.reconcilePrimary(ctx, cluster)
-	if err != nil {
+	// Instance promotion will not automatically load the changed configuration files.
+	// Therefore it should not be counted as "a restart" to prevent instance restart.
```
Comment (jsilvela) [inline internal/management/controller/instance_controller.go:175]:
```suggestion
	// Instance promotion will not automatically load the changed configuration files.
	// Therefore it should not be counted as "a restart".
```

**Comment by litaocdl** [comment]
update the pr by removing the unused variable

**Review by fcanovai — APPROVED** [review]

**Review by mnencia — APPROVED** [review]

File: internal/management/controller/instance_controller.go (hunk 1 above)
Comment (mnencia) [reply internal/management/controller/instance_controller.go]: If we don't update the status, the Status patch step is retried.
The drop connection is not vital. It is there only to prevent a long-running session through the read-only service from silently becoming a read-write one.
