### PR TITLE
fix(roles): properly quote inRoles in SQL statements

### LINKED ISSUE #6337: [Bug]: inRoles not properly escaped while creating role
### Is there an existing issue already for this bug?

- [x] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [x] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [x] I have read the troubleshooting guide and I think this is a new bug.

### Contact Details

hello@maximilian.dev

### Version

1.24.0

### What version of Kubernetes are you using?

1.29

### What is your Kubernetes environment?

Cloud: Amazon EKS

### How did you install the operator?

Helm

### Problem description
I want to create a role, that is in another role, containing a hyphen. The role itself can contain a hyphen and is properly escaped, but the `inRoles` attribute is not properly escaped.

### Workaround
1. Edit the cluster resource to not contain the role on creation.
2. Let the operator Reconcile
3. Add the role again

### Side question
Is it intentional, that there is no error (or warning) message in the operator log indicating, that the reconcilation failed due to an error? There is also no message in status. It just displays the role in the `pending-reconciliation` attribute. If it's not intentional I will create another issue for that.

### Side note
I'm using CNPG Operator 1.24.1, the checkbox doesn't let me select that.

### Cluster resource

```shell
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: database
status:
  ...
  managedRolesStatus:
    byStatus:
      pending-reconciliation:
        - myuser
      reconciled:
        - app
      reserved:
        - postgres
        - streaming_replica
    passwordStatus:
      app:
        transactionID: 741
  phase: Cluster in healthy state
  ...
spec:
  ...
  managed:
    roles:
      - connectionLimit: -1
        ensure: present
        inherit: true
        login: true
        name: app
      - connectionLimit: -1
        ensure: present
        inRoles:
          - pg_read_all_data
          - pg_write_all_data
        inherit: true
        name: my-role
      - connectionLimit: -1
        ensure: present
        inRoles:
          - my-role
        inherit: true
        login: true
        name: myuser
        passwordSecret:
          name: myuser
   ...
```

### Relevant log output

```shell
{
  "level": "trace",
  "ts": "2024-12-17T12:54:42.387709451Z",
  "logger": "instance-manager",
  "msg": "Invoked",
  "caller": "internal/management/controller/roles/postgres.go:138",
  "logging_pod": "database-1",
  "role": {
    "name": "myuser",
    "inherit": true,
    "login": true,
    "connectionLimit": -1,
    "validUntil": null,
    "inRoles": [
      "my-role"
    ]
  }
}
{
  "level": "debug",
  "ts": "2024-12-17T12:54:42.387771178Z",
  "logger": "instance-manager",
  "msg": "Creating",
  "caller": "internal/management/controller/roles/postgres.go:148",
  "logging_pod": "database-1",
  "query": "CREATE ROLE \"myuser\"  NOBYPASSRLS NOCREATEDB NOCREATEROLE INHERIT LOGIN NOREPLICATION NOSUPERUSER CONNECTION LIMIT -1 IN ROLE my-role  PASSWORD 'NCq19tGI75eXTKOLSCl3o4wSyAERtBaP'"
}
{
  "level": "info",
  "ts": "2024-12-17T12:54:42.390801418Z",
  "logger": "postgres",
  "msg": "record",
  "logging_pod": "database-1",
  "record": {
    "log_time": "2024-12-17 12:54:42.390 UTC",
    "user_name": "postgres",
    "database_name": "postgres",
    "process_id": "213",
    "connection_from": "[local]",
    "session_id": "67617492.d5",
    "session_line_num": "1",
    "command_tag": "idle",
    "session_start_time": "2024-12-17 12:54:42 UTC",
    "virtual_transaction_id": "70/5",
    "transaction_id": "0",
    "error_severity": "ERROR",
    "sql_state_code": "42601",
    "message": "syntax error at or near \"-\"",
    "query": "CREATE ROLE \"myuser\"  NOBYPASSRLS NOCREATEDB NOCREATEROLE INHERIT LOGIN NOREPLICATION NOSUPERUSER CONNECTION LIMIT -1 IN ROLE my-role  PASSWORD 'NCq19tGI75eXTKOLSCl3o4wSyAERtBaP'",
    "query_pos": "148",
    "application_name": "cnpg-instance-manager",
    "backend_type": "client backend",
    "query_id": "0"
  }
}
{
  "level": "error",
  "ts": "2024-12-17T12:54:42.390951162Z",
  "logger": "instance-manager",
  "msg": "while performing CREATE",
  "logging_pod": "database-1",
  "role": "myuser",
  "error": "while trying to CREATE: while creating role myuser with DRM: ERROR: syntax error at or near \"-\" (SQLSTATE 42601)",
  "stacktrace": "github.com/cloudnative-pg/machinery/pkg/log.(*logger).Error\n\tpkg/mod/github.com/cloudnative-pg/machinery@v0.0.0-20241014090714-c27747f9974b/pkg/log/log.go:125\ngithub.com/cloudnative-pg/cloudnative-pg/internal/management/controller/roles.(*RoleSynchronizer).applyRoleActions.func1\n\tinternal/management/controller/roles/runnable.go:236\ngithub.com/cloudnative-pg/cloudnative-pg/internal/management/controller/roles.(*RoleSynchronizer).applyRoleActions\n\tinternal/management/controller/roles/runnable.go:260\ngithub.com/cloudnative-pg/cloudnative-pg/internal/management/controller/roles.(*RoleSynchronizer).synchronizeRoles\n\tinternal/management/controller/roles/runnable.go:198\ngithub.com/cloudnative-pg/cloudnative-pg/internal/management/controller/roles.(*RoleSynchronizer).reconcile\n\tinternal/management/controller/roles/runnable.go:151\ngithub.com/cloudnative-pg/cloudnative-pg/internal/management/controller/roles.(*RoleSynchronizer).Start.func1\n\tinternal/management/controller/roles/runnable.go:103"
}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by gabriele-wolfox**
This patch fixes an issue where the `inRoles` parameter was not properly quoted in SQL statements, which could cause syntax errors if the role name contains special characters.

Closes #6337 

## Release notes

Properly quote `inRoles` in SQL statements to prevent potential syntax errors in the generated SQL.

### CODE REVIEW

File: internal/management/controller/roles/postgres.go [hunk 1]
```diff
@@ -301,7 +301,13 @@ func GetParentRoles(ctx context.Context, db *sql.DB, role DatabaseRole) ([]strin
 
 func appendInRoleOptions(role DatabaseRole, query *strings.Builder) {
 	if len(role.InRoles) > 0 {
-		query.WriteString(fmt.Sprintf(" IN ROLE %s ", strings.Join(role.InRoles, ",")))
+		quotedInRoles := make([]string, len(role.InRoles))
+
+		for i, inRole := range role.InRoles {
+			quotedInRoles[i] = pq.QuoteIdentifier(inRole)
```
Comment (mnencia) [inline internal/management/controller/roles/postgres.go:307]:
```suggestion
			quotedInRoles[i] = pgx.Identifier{inRole}.Sanitize()
```

**Review by mnencia — CHANGES_REQUESTED** [review]

File: internal/management/controller/roles/postgres.go (hunk 1 above)
Comment (mnencia) [reply internal/management/controller/roles/postgres.go:307]: We don't use `pq.QuoteIdentifier`. All the codebase uses `pgx.Identifier` instead.

**Review by mnencia — APPROVED** [review]

**Comment by mnencia** [comment]
> @mnencia @gabriele-wolfox this is only for 1.24 right? 1.22 and 1.23 shouldn't be having this PR ?

Declarative role management has been introduced in 1.20, so it needs to be backported to all the branches.

**Comment by leonardoce** [comment]
I started a few E2e runs on this:

```
STATUS  TITLE              WORKFLOW           BRANCH        EVENT              ID           ELAPSED   AGE
*       continuous-del...  continuous-del...  dev/cnp-5756  workflow_dispatch  12410155110  7s        less than a mi...
*       continuous-del...  continuous-del...  dev/cnp-5756  workflow_dispatch  12410154776  8s        less than a mi...
*       continuous-del...  continuous-del...  dev/cnp-5756  workflow_dispatch  12410154394  10s       less than a mi...
* ```
*

**Comment by mnencia** [comment]
* https://github.com/EnterpriseDB/cloudnative-pg/actions/runs/12415238247
* https://github.com/EnterpriseDB/cloudnative-pg/actions/runs/12415243728

**Review by leonardoce — APPROVED** [review]
