### PR TITLE
fix: instance manager stuck if PostgreSQL doesn't start

### LINKED ISSUE #4433: [Bug]: The instance manager is not able to unfence PG after a previous unfence operation failed
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Contact Details

leonardo.cecchi@enterprisedb.com

### Version

1.23.0

### What version of Kubernetes are you using?

1.30 (unsuppprted)

### What is your Kubernetes environment?

Self-managed: kind (evaluation)

### How did you install the operator?

YAML manifest

### What happened?

If an unfence request fails because PostgreSQL cannot start up, subsequent unfence requests will fail, too, because the instance manager won't start PostgreSQL up again.

These steps will reproduce this weird situation programmatically and every time:

1. Applying the attached cluster definition (this is the minimal example, where instances have been replaced by 1 [even if the number of instances should not be relevant])
2. Fence the primary instance (`./bin/kubectl-cnpg fencing on cluster-example 1`) -- This will result in PG to shut down
3. Remove every WAL file from PGDATA (`kubectl exec -ti cluster-example-1 -- bash -c 'rm $PGDATA/pg_wal/*'`)
4. Lift fencing (`./bin/kubectl-cnpg fencing off cluster-example 1`) -- This will result in PG to start up again, and fail to start up
5. Fence the instance again (`./bin/kubectl-cnpg fencing on cluster-example 1`)
6. Unfence the instance (`./bin/kubectl-cnpg fencing off cluster-example 1`) -- The instance manager will not even try to start PostgreSQL

I'm working on a patch to fix this issue.

### Cluster resource

```shell
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example
spec:
  instances: 1

  storage:
    size: 1Gi
```

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by leonardoce**
If a primary PostgreSQL instance fails to start after being stopped, the instance manager is indefinitely waiting for it to start running the configuration queries.

This patch creates a separate context for each postmaster process and runs the configuration queries in a parallel goroutine, canceling it as soon as the postmaster finishes.

Fixes: #4433

### CODE REVIEW

File: internal/cmd/manager/instance/run/lifecycle/run.go [hunk 1]
```diff
@@ -67,12 +73,13 @@ func (i *PostgresLifecycle) runPostgresAndWait(ctx context.Context) <-chan error
 		}
 
 		// once the database will be up we'll connect and setup everything required
-		err = configureInstancePermissions(ctx, i.instance)
-		if err != nil {
-			contextLogger.Error(err, "Unable to update PostgreSQL roles and permissions")
-			errChan <- err
-			return
-		}
+		go func() {
```
Comment (jsilvela) [inline internal/cmd/manager/instance/run/lifecycle/run.go:76]: I worry about this being a goroutine without a waitgroup or similar.
Seems if there is an error here but it doesn't happen super quick, we could ignore it.

**Comment by leonardoce** [comment]
E2e tests are all green!

**Review by armru — APPROVED** [review]

**Comment by mnencia** [comment]
I think the concurrency in this code is difficult to understand correctly. I would like to have some comments to help understanding it.

**Review by mnencia — APPROVED** [review]

**Review by fcanovai — APPROVED** [review]
