### PR TITLE
fix(instance-manager): use pgdata content to discover PostgreSQL version

### LINKED ISSUE #6658: [Bug]: Configuration logic in the instance manager uses heuristic instead of on-disk version
### Is there an existing issue already for this bug?

- [x] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [x] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [x] I have read the troubleshooting guide and I think this is a new bug.

### Contact Details

marco.nenciarini@enterprisedb.com

### Version

trunk (main)

### What version of Kubernetes are you using?

1.32

### What is your Kubernetes environment?

Self-managed: kind (evaluation)

### How did you install the operator?

YAML manifest

### What happened?

The configuration generator in the instance manager attempts to guess the PostgreSQL version using a heuristic based on the image name that is present in the status. This is inaccurate, as the instance manager has first-hand access to the data directory.

The instance manager should inspect the data directory on disk to determine the PostgreSQL major version, ensuring accurate configuration generation regardless of the cluster status's content.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by mnencia**
Use a precise check of the data directory to determine the PostgreSQL major version during PostgreSQL configuration generation.

Closes #6658

### CODE REVIEW

File: internal/cmd/manager/instance/run/lifecycle/run.go [hunk 1]
```diff
@@ -228,10 +228,10 @@ func configureStreamingReplicaUser(tx *sql.Tx) (bool, error) {
 }
 
 // configurePgRewindPrivileges ensures that the StreamingReplicationUser has enough rights to execute pg_rewind
-func configurePgRewindPrivileges(majorVersion *semver.Version, hasSuperuser bool, tx *sql.Tx) error {
+func configurePgRewindPrivileges(majorVersion semver.Version, hasSuperuser bool, tx *sql.Tx) error {
 	// We need the superuser bit for the streaming-replication user since pg_rewind in PostgreSQL <= 10
 	// will require it.
-	if majorVersion != nil && majorVersion.Major <= 10 {
```
Comment (armru) [inline internal/cmd/manager/instance/run/lifecycle/run.go]: I made the semver as required, given that we cannot make a decision otherwise.

**Review by armru — APPROVED** [review]

File: pkg/management/postgres/utils/version.go [hunk 2]
```diff
@@ -38,25 +38,30 @@ func GetPgVersion(db *sql.DB) (*semver.Version, error) {
...
+		Minor: (versionInt / 100) % 100,
+		Patch: versionInt % 100,
 	}, nil
 }
 
-// GetMajorVersion read the PG_VERSION file in the data directory
+// GetPgdataVersion read the PG_VERSION file in the data directory
 // returning the major version of the database
-func GetMajorVersion(pgData string) (int, error) {
+func GetPgdataVersion(pgData string) (semver.Version, error) {
```
Comment (jsilvela) [inline pkg/management/postgres/utils/version.go:55]: I'm not sure I agree with the new signature.
The PG_VERSION contrains only the major number, nothing else.
I don't think this is the right place to return a semver.Version

File: internal/cmd/manager/instance/run/lifecycle/run.go [hunk 3]
```diff
@@ -227,10 +228,10 @@ func configureStreamingReplicaUser(tx *sql.Tx) (bool, error) {
 }
 
 // configurePgRewindPrivileges ensures that the StreamingReplicationUser has enough rights to execute pg_rewind
-func configurePgRewindPrivileges(majorVersion int, hasSuperuser bool, tx *sql.Tx) error {
+func configurePgRewindPrivileges(majorVersion semver.Version, hasSuperuser bool, tx *sql.Tx) error {
```
Comment (jsilvela) [inline internal/cmd/manager/instance/run/lifecycle/run.go:231]: and here we change the signature to consume a semver but only require the major. Not an improvement IMO, except perhaps we can use `unit64` better, as would be done in Semver

File: pkg/management/postgres/configuration.go [hunk 4]
```diff
@@ -65,11 +67,12 @@ func (instance *Instance) RefreshConfigurationFilesFromCluster(
 	cluster *apiv1.Cluster,
 	preserveUserSettings bool,
 ) (bool, error) {
-	postgresConfiguration, sha256, err := createPostgresqlConfiguration(cluster, preserveUserSettings)
+	majorVersion, err := postgresutils.GetPgdataVersion(instance.PgData)
```
Comment (jsilvela) [inline pkg/management/postgres/configuration.go:70]: and here again you get the full semver but only consume the major

**Review by jsilvela — COMMENTED** [review]
I'm not seeing the point of returning a Semver when we read PG_VERSION.
Isn't it better to just return and consume a `uint64`?

**Comment by jsilvela** [comment]
Clarified my objections about the signature with Marco.

**Review by jsilvela — APPROVED** [review]

File: pkg/management/postgres/utils/version.go (hunk 2 above)
Comment (mnencia) [reply pkg/management/postgres/utils/version.go:55]: The goal is to eliminate confusion and assign a clear, specific type to the value. We've already made similar adjustments for the int/uint version in the past, with consensus that using `semver` helps prevent misinterpretation when the source of the values isn't immediately apparent.
