### PR TITLE
fix(instance_replica): include dbname in primary_conninfo for replication configuration

### LINKED ISSUE #5917: [Bug]: Cannot use PG 17 replication slot failover (dbname must be specified in primary_conninfo)
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Contact Details

_No response_

### Version

1.24.0

### What version of Kubernetes are you using?

1.31

### What is your Kubernetes environment?

Self-managed: k3s

### How did you install the operator?

Helm

### What happened?

I'm trying to test the new failover slots into PG 17. I am able to turn on hot_standby_feedback and sync_replication_slots but the slots never synchronize. The replica is logging an error from the "slotsync worker" that says that dbname must be specified in the primary_conninfo in order to enable failover sync. [According to the PG docs](https://www.postgresql.org/docs/current/runtime-config-replication.html#GUC-PRIMARY-CONNINFO) the dbname parameter is used exclusively for slot synchronization, so the issue might be relatively straightforward to solve.

### Cluster resource

_No response_

### Relevant log output

```shell
{"level":"info","ts":"2024-10-21T23:57:29.986731099Z","logger":"postgres","msg":"record","logging_pod":"best-cluster-1","record":{"log_time":"2024-10-21 23:57:29.986 UTC","process_id":"4376","session_id":"6716ea69.1118","session_line_num":"2","session_start_time":"2024-10-21 23:57:29 UTC","virtual_transaction_id":"92/0","transaction_id":"0","error_severity":"ERROR","sql_state_code":"22023","message":"replication slot synchronization requires \"dbname\" to be specified in \"primary_conninfo\"","backend_type":"slotsync worker","query_id":"0"}}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by quajones**
closes #5917 include dbname within primary_conninfo for replica configuration to support replication slot synchronization and enable logical replication failover

> replication slot synchronization requires "dbname" to be specified in "primary_conninfo"

### CODE REVIEW

File: pkg/management/postgres/instance_replica.go [hunk 1]
```diff
@@ -64,7 +64,8 @@ func (instance *Instance) RefreshReplicaConfiguration(
 
 func (instance *Instance) writeReplicaConfigurationForReplica(cluster *apiv1.Cluster) (changed bool, err error) {
 	slotName := cluster.GetSlotNameFromInstanceName(instance.GetPodName())
-	return UpdateReplicaConfiguration(instance.PgData, instance.GetPrimaryConnInfo(), slotName)
+	primaryConnInfo := instance.GetPrimaryConnInfo() + fmt.Sprintf(" dbname=%v", cluster.GetApplicationDatabaseName())
```
Comment (mnencia) [inline pkg/management/postgres/instance_replica.go:67]: I would use the "postgres" database here because it always exists and does not require any additional logic.

Comment (quajones) [reply pkg/management/postgres/instance_replica.go]: thanks! this has been updated

**Comment by kndoni** [comment]
would it be good to have this configurable, because there are use cases when dbname is not postgres but its another database

**Comment by mnencia** [comment]
> would it be good to have this configurable, because there are use cases when dbname is not postgres but its another database

The instance manager always uses the `postgres` database when connecting to the local instance, so its existence is mandatory. The dbname parameter in the primary conninfo has no other uses than to specify a database that must exist, so I see no reason to make it configurable.

**Comment by kndoni** [comment]
> > would it be good to have this configurable, because there are use cases when dbname is not postgres but its another database
> 
> The instance manager always uses the `postgres` database when connecting to the local instance, so its existence is mandatory. The dbname parameter in the primary conninfo has no other uses than to specify a database that must exist, so I see no reason to make it configurable.

But in my usecase I have enabled failover for logical replication in postgresql 17 instance. And when one of the standby replica-s is promoted as primary the logical replication slot won't switchover because of the missing dbname in primary_conninfo. But in my case I am having the logical replication in a different database not in the postgresql. So in this case I need to configure dbname parameter in primary_conninfo

**Comment by mnencia** [comment]
> But in my usecase I have enabled failover for logical replication in postgresql 17 instance. And when one of the standby replica-s is promoted as primary the logical replication slot won't switchover because of the missing dbname in primary_conninfo. But in my case I am having the logical replication in a different database not in the postgresql. So in this case I need to configure dbname parameter in primary_conninfo

I think you misunderstood the usage of the `dbname` parameter here. It doesn't need to be the name of the database where the replication slot operates, but just a valid database where the slot replication code could run the functions to inspect the actual slot's position. So, setting it to `postgres` is perfectly safe, as the whole operator would stop working if you delete or rename that database. See the Postgres patch for further details https://github.com/postgres/postgres/commit/93db6cbda037f1be9544932bd9a785dabf3ff712

**Review by mnencia — APPROVED** [review]

**Review by sxd — APPROVED** [review]
