### PR TITLE
fix(plugin): handle errors during the `status` command execution

### LINKED ISSUE #4847: [Bug]: plugin command status fails getting PDB
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Contact Details

_No response_

### Version

1.23.2

### What version of Kubernetes are you using?

1.30 (unsupported)

### What is your Kubernetes environment?

Self-managed: kind (evaluation)

### How did you install the operator?

YAML manifest

### What happened?

When the user doesn't have any permission at all over the `poddisruptionbudgets` the status command will fail with the following error:
```
 Error: while extracting PodDisruptionBudgetList: poddisruptionbudgets.policy is forbidden: User "sxd" cannot list resource "poddisruptionbudgets" in API group "policy" in the namespace "jg"
```
And it doesn't show anything even if I have access to the cluster.

### Cluster resource

_No response_

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by armru**
This patch ensures that we continue the `status` command execution even if we encounter an error while trying to fetch the status of the instances.

Closes #4847

### CODE REVIEW

**Review by sxd — APPROVED** [review]

File: internal/cmd/plugin/status/status.go [hunk 1]
```diff
@@ -19,6 +19,7 @@ package status
 import (
 	"context"
 	"fmt"
+	apierrs "k8s.io/apimachinery/pkg/api/errors"
```
Comment (gabriele-wolfox) [inline internal/cmd/plugin/status/status.go:22]: Linter issue

**Review by gabriele-wolfox — APPROVED** [review]

**Review by gabriele-wolfox — APPROVED** [review]

**Review by mnencia — APPROVED** [review]
