### PR TITLE
fix: initialize `override.conf` before invoking `pg_rewind`

### LINKED ISSUE #6669: [Bug]: pg_rewind fails if override.conf is empty
### Is there an existing issue already for this bug?

- [x] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [x] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [x] I have read the troubleshooting guide and I think this is a new bug.

### Contact Details

_No response_

### Version

1.25 (latest patch)

### What version of Kubernetes are you using?

1.32

### What is your Kubernetes environment?

Self-managed: kind (evaluation)

### How did you install the operator?

YAML manifest

### What happened?

If the `override.conf` file is empty for any reason, the `pg_rewind` command will fail when demoting a former primary. While this scenario is uncommon—since `override.conf` is typically initialized during cluster creation—it’s a good practice to account for such edge cases. To enhance robustness, ensure that the `override.conf` file is properly initialized before executing `pg_rewind` with the `--restore-target-wal` option.

### Cluster resource

```shell

```

### Relevant log output

```shell
cluster-example-1 postgres {"level":"info","ts":"2025-01-27T09:48:50.115968576Z","msg":"Starting up pg_rewind","logger":"instance-manager","logging_pod":"cluster-example-1","controller":"instance-cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"073e3c60-79ce-463e-86ec-989170dd0e37","logging_pod":"cluster-example-1","pgdata":"/var/lib/postgresql/data/pgdata","options":["-P","--source-server","host=cluster-example-rw user=streaming_replica port=5432 sslkey=/controller/certificates/streaming_replica.key sslcert=/controller/certificates/streaming_replica.crt sslrootcert=/controller/certificates/server-ca.crt application_name=cluster-example-1 sslmode=verify-ca dbname=postgres","--target-pgdata","/var/lib/postgresql/data/pgdata","--restore-target-wal"]}
cluster-example-1 postgres {"level":"info","ts":"2025-01-27T09:48:50.15143687Z","logger":"pg_rewind","msg":"pg_rewind: error: \"restore_command\" is not set in the target cluster","pipe":"stderr","logging_pod":"cluster-example-1"}
cluster-example-1 postgres {"level":"error","ts":"2025-01-27T09:48:50.152156925Z","msg":"Failed to execute pg_rewind","logger":"instance-manager","logging_pod":"cluster-example-1","controller":"instance-cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"073e3c60-79ce-463e-86ec-989170dd0e37","logging_pod":"cluster-example-1","options":["-P","--source-server","host=cluster-example-rw user=streaming_replica port=5432 sslkey=/controller/certificates/streaming_replica.key sslcert=/controller/certificates/streaming_replica.crt sslrootcert=/controller/certificates/server-ca.crt application_name=cluster-example-1 sslmode=verify-ca dbname=postgres","--target-pgdata","/var/lib/postgresql/data/pgdata","--restore-target-wal"],"error":"exit status 1","stacktrace":"github.com/cloudnative-pg/machinery/pkg/log.(*logger).Error\n\t/Users/mnencia/.asdf/installs/golang/1.23.4/packages/pkg/mod/github.com/cloudnative-pg/machinery@v0.0.0-20250102082645-95c37fe624d0/pkg/log/log.go:125\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/postgres.(*Instance).Rewind\n\tpkg/management/postgres/instance.go:1040\ngithub.com/cloudnative-pg/cloudnative-pg/internal/management/controller.(*InstanceReconciler).verifyPgDataCoherenceForPrimary\n\tinternal/management/controller/instance_startup.go:271\ngithub.com/cloudnative-pg/cloudnative-pg/internal/management/controller.(*InstanceReconciler).initialize\n\tinternal/management/controller/instance_controller.go:408\ngithub.com/cloudnative-pg/cloudnative-pg/internal/management/controller.(*InstanceReconciler).Reconcile\n\tinternal/management/controller/instance_controller.go:164\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile\n\t/Users/mnencia/.asdf/installs/golang/1.23.4/packages/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.4/pkg/internal/controller/controller.go:116\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/Users/mnencia/.asdf/installs/golang/1.23.4/packages/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.4/pkg/internal/controller/controller.go:303\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/Users/mnencia/.asdf/installs/golang/1.23.4/packages/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.4/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/Users/mnencia/.asdf/installs/golang/1.23.4/packages/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.4/pkg/internal/controller/controller.go:224"}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by mnencia**
This patch ensures `override.conf` is correctly initialized before invoking `pg_rewind`, resolving an issue where configuration misalignment could cause failures during the demotion of a former primary.  

Closes #6669  

## Release notes:  

Ensure `override.conf` is initialized correctly before invoking `pg_rewind` to avoid failures during primary role changes.

### CODE REVIEW

**Comment by mnencia** [comment]
This patch is built on top of #6659 and deeds it merged before.

File: internal/management/controller/instance_startup.go [hunk 1]
```diff
@@ -262,13 +263,7 @@ func (r *InstanceReconciler) verifyPgDataCoherenceForPrimary(ctx context.Context
 			return fmt.Errorf("while ensuring all WAL files are archived: %w", err)
 		}
 
-		// pg_rewind could require a clean shutdown of the old primary to
-		// work. Unfortunately, if the old primary is already clean starting
-		// it up may make it advance in respect to the new one.
-		// The only way to check if we really need to start it up before
-		// invoking pg_rewind is to try using pg_rewind and, on failures,
-		// retrying after having started up the instance.
-		err = r.instance.Rewind(ctx, pgVersion)
```
Comment (mnencia) [inline internal/management/controller/instance_startup.go:271]: I removed the comment because it is outdated. Since version 13 pg_rewind automatically makes sure that the instance is cleanly shutdown.

**Review by armru — APPROVED** [review]

**Review by jsilvela — APPROVED** [review]
