### PR TITLE
fix: avoid creating Pods for an incomplete group of PVCs

### LINKED ISSUE #683: Avoid creating Pods for an incomplete group of PVCs
When a cluster is configured with separate storage for WAL files,
if you delete a Pod and only one of their PVCs, the operator tries to recreate the Pod
even if one of its PVCs is not present anymore.

Instead, we should ignore the unusable PVC and provision a new instance to reach the correct number of replicas.

### PR DESCRIPTION
**Pull request by mnencia**
Closes #683

Signed-off-by: Marco Nenciarini <marco.nenciarini@enterprisedb.com>

### CODE REVIEW

**Review by armru — APPROVED** [review]

File: pkg/specs/pvcs.go [hunk 1]
```diff
@@ -178,84 +184,123 @@ pvcLoop:
...
+				result.Unusable = append(result.Unusable, pvcNames...)
+				continue instancesLoop
 			}
 		}
 
-		if pvc.Annotations[PVCStatusAnnotationName] != PVCStatusReady {
-			// This PVC has not a Job nor a Pod using it, but it is not marked as PVCStatusReady
-			// we need to ignore it here
-			continue
+		// If we have more PVC than expected, the extra PVCs are unusable
```
Comment (leonardoce) [inline pkg/specs/pvcs.go:224]: If I understand correctly, what happens here is that we don't have "**more PVC than expected**" (as in count) but we found a PVC which we don't expect (as in subsets definition).

If I'm correct, perhaps we could fix this comment.

File: pkg/specs/pvcs.go [hunk 2]
```diff
@@ -178,84 +184,123 @@ pvcLoop:
...
-			// we lost some pvc null them all
-			for _, index := range indexOfFoundPVCs {
-				result.Dangling = append(result.Dangling, result.Healthy[index])
-				result.Healthy = removeElementByIndex(result.Healthy, index)
+		// At this point the PVCs are dangling, so we need to check if some of them has
+		// a PVC status annotation marking it as non-ready.
+		// In that case, all the instance PVCs are unusable
+		for _, pvc := range pvcs {
+			// We ignore any PVC that is not expected
+			if !slices.Contains(expectedPVCs, pvc.Name) {
```
Comment (leonardoce) [inline pkg/specs/pvcs.go:267]: Is this really possible? We already have https://github.com/cloudnative-pg/cloudnative-pg/pull/684/files#diff-fd3956fd8d840a5772b8b430eca9c8eb8b36d261a1c91e240052ae46dd2e4964R226

**Review by leonardoce — APPROVED** [review]

File: pkg/specs/pvcs.go (hunk 1 above)
Comment (mnencia) [reply pkg/specs/pvcs.go:224]: Yes, you are right

File: pkg/specs/pvcs.go (hunk 2 above)
Comment (mnencia) [reply pkg/specs/pvcs.go:267]: That check doesn't remove the extra PVC from the list, so we need to filter them in this check, otherwise they could invalidate the whole instance.

Comment (mnencia) [reply pkg/specs/pvcs.go:267]: Here we are iterating over PVCs not PVC names because we need to check the annotations.

File: pkg/specs/pvcs.go (hunk 1 above)
Comment (armru) [reply pkg/specs/pvcs.go:224]: I agree
