### PR TITLE
fix: ensure HA slots don't hold xmin

### LINKED ISSUE #4802: [Bug]: xmin on standby cluster replication slots causing heavy io on primary due to permanent autovacuum
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Contact Details

smiyc@pm.me

### Version

1.23.1

### What version of Kubernetes are you using?

other (unsupported)

### What is your Kubernetes environment?

Other

### How did you install the operator?

YAML manifest

### What happened?

increasing disk iops / throughput on the primary.
The reason for the problem is an table which is autovacuumed all the time but has a lot of dead tuples which are not removed.
We checked for long running transactions, perpared transcation and the replication slots.

On replication slot is not advancing xmin
keycloak-6 (primary)
```
# select * from pg_replication_slots ;
┌─[ RECORD 1 ]────────┬──────────────────┐
│ slot_name           │ _cnpg_keycloak_3 │
│ plugin              │ ∅                │
│ slot_type           │ physical         │
│ datoid              │ ∅                │
│ database            │ ∅                │
│ temporary           │ f                │
│ active              │ t                │
│ active_pid          │ 341260           │
│ xmin                │ 91922262         │
│ catalog_xmin        │ ∅                │
│ restart_lsn         │ 8B6/90E3C120     │
│ confirmed_flush_lsn │ ∅                │
│ wal_status          │ reserved         │
│ safe_wal_size       │ 96638615264      │
│ two_phase           │ f                │
│ conflicting         │ ∅                │
├─[ RECORD 2 ]────────┼──────────────────┤
│ slot_name           │ _cnpg_keycloak_5 │
│ plugin              │ ∅                │
│ slot_type           │ physical         │
│ datoid              │ ∅                │
│ database            │ ∅                │
│ temporary           │ f                │
│ active              │ t                │
│ active_pid          │ 23293            │
│ xmin                │ 96148135         │
│ catalog_xmin        │ ∅                │
│ restart_lsn         │ 8B6/90E3C120     │
│ confirmed_flush_lsn │ ∅                │
│ wal_status          │ reserved         │
│ safe_wal_size       │ 96638615264      │
│ two_phase           │ f                │
│ conflicting         │ ∅                │
└─────────────────────┴──────────────────┘
```
Then we checkt the replicaition slots on the standby clusters
keycloak-5 (standby)
```
postgres=# select * from pg_replication_slots ;
┌─[ RECORD 1 ]────────┬──────────────────┐
│ slot_name           │ _cnpg_keycloak_3 │
│ plugin              │ ∅                │
│ slot_type           │ physical         │
│ datoid              │ ∅                │
│ database            │ ∅                │
│ temporary           │ f                │
│ active              │ f                │
│ active_pid          │ ∅                │
│ xmin                │ ∅                │
│ catalog_xmin        │ ∅                │
│ restart_lsn         │ 8B6/F9078528     │
│ confirmed_flush_lsn │ ∅                │
│ wal_status          │ reserved         │
│ safe_wal_size       │ 9678608138240    │
│ two_phase           │ f                │
│ conflicting         │ ∅                │
└─────────────────────┴──────────────────┘
```
keycloak-3 (standby)
```
postgres=# select * from pg_replication_slots ;
┌─[ RECORD 1 ]────────┬──────────────────┐
│ slot_name           │ _cnpg_keycloak_5 │
│ plugin              │ ∅                │
│ slot_type           │ physical         │
│ datoid              │ ∅                │
│ database            │ ∅                │
│ temporary           │ f                │
│ active              │ f                │
│ active_pid          │ ∅                │
│ xmin                │ 91922262         │
│ catalog_xmin        │ ∅                │
│ restart_lsn         │ 8B6/F9520BD8     │
│ confirmed_flush_lsn │ ∅                │
│ wal_status          │ reserved         │
│ safe_wal_size       │ 9678608138240    │
│ two_phase           │ f                │
│ conflicting         │ ∅                │
└─────────────────────┴──────────────────┘
```
And saw, that _cnpg_keycloak_5 has xmin set.
Now the question is how to get rid of the xmin, so that vacuum can clenaup the table?
cheers

### Cluster resource

```shell
Name:         keycloak
Namespace:    cnpg-test
Labels:       release=prometheus-operator
Annotations:  cnpg.io/reloadedAt: 2024-04-28T22:56:59.518845+02:00
              kubectl.kubernetes.io/restartedAt: 2024-04-28T22:58:44+02:00
API Version:  postgresql.cnpg.io/v1
Kind:         Cluster
Metadata:
  Creation Timestamp:  2024-04-18T07:06:22Z
  Generation:          30
  Resource Version:    678335599
  UID:                 b2548d1c-7666-43bb-814a-7cdd7bd48dae
Spec:
  Affinity:
    Enable Pod Anti Affinity:  true
    Pod Anti Affinity Type:    preferred
    Topology Key:              kubernetes.io/hostname
  Backup:
    Barman Object Store:
      Data:
        Immediate Checkpoint:  true
        Jobs:                  4
      Destination Path:        s3://cnpg-test
      Endpoint CA:
        Key:         tls.crt
        Name:        xxx-ca
      Endpoint URL:  https://xxx.net
      s3Credentials:
        Access Key Id:
          Key:   ACCESS_KEY_ID
          Name:  xxx-creds
        Secret Access Key:
          Key:      ACCESS_SECRET_KEY
          Name:     xxx-creds
      Server Name:  keycloak
      Wal:
        Max Parallel:  2
    Retention Policy:  31d
    Target:            prefer-standby
  Bootstrap:
    Initdb:
      Data Checksums:  true
      Database:        app
      Encoding:        UTF8
      Locale C Type:   C
      Locale Collate:  C
      Owner:           app
  Enable PDB:               true
  Enable Superuser Access:  false
  Failover Delay:           0
  Image Name:               xxx/cnpg:16.2
  Image Pull Secrets:
    Name:     docker-registry-repo-xxx-at-auth
  Instances:  3
  Log Level:  info
  Max Sync Replicas:  1
  Min Sync Replicas:  1
  Monitoring:
    Custom Queries Config Map:
      Key:                    queries
      Name:                   cnpg-default-monitoring
    Disable Default Queries:  false
    Enable Pod Monitor:       true
  Node Maintenance Window:
    In Progress:  false
    Reuse PVC:    true
  Postgres GID:   26
  Postgres UID:   26
  Postgresql:
    Parameters:
      archive_mode:                      on
      archive_timeout:                   5min
      auto_explain.log_min_duration:     5000ms
      checkpoint_timeout:                30min
      client_connection_check_interval:  60
      dynamic_shared_memory_type:        posix
      effective_cache_size:              6GB
      effective_io_concurrency:          100
      hot_standby_feedback:              on
      log_destination:                   csvlog
      log_directory:                     /controller/log
      log_executor_stats:                off
      log_filename:                      postgres
      log_line_prefix:                   %m [%p] %u@%d [%a]
      log_lock_waits:                    on
      log_rotation_age:                  0
      log_rotation_size:                 0
      log_statement:                     ddl
      log_timezone:                      Europe/Vienna
      log_truncate_on_rotation:          false
      logging_collector:                 on
      maintenance_work_mem:              512MB
      max_connections:                   400
      max_parallel_workers:              32
      max_replication_slots:             32
      max_slot_wal_keep_size:            90GB
      max_wal_size:                      5120MB
      max_worker_processes:              32
      min_wal_size:                      512MB
      pg_stat_statements.max:            10000
      pg_stat_statements.track:          all
      random_page_cost:                  1.25
      shared_buffers:                    2GB
      shared_memory_type:                mmap
      shared_preload_libraries:          
      ssl_max_protocol_version:          TLSv1.3
      ssl_min_protocol_version:          TLSv1.3
      superuser_reserved_connections:    3
      tcp_keepalives_count:              3
      tcp_keepalives_idle:               60
      tcp_keepalives_interval:           30
      Timezone:                          Europe/Vienna
      track_activities:                  true
      track_counts:                      true
      track_functions:                   pl
      track_io_timing:                   on
      track_wal_io_timing:               true
      wal_keep_size:                     512MB
      wal_level:                         logical
      wal_log_hints:                     on
      wal_receiver_timeout:              5s
      wal_sender_timeout:                5s
      work_mem:                          5242kB
    Sync Replica Election Constraint:
      Enabled:              false
  Primary Update Method:    restart
  Primary Update Strategy:  unsupervised
  Replication Slots:
    High Availability:
      Enabled:      true
      Slot Prefix:  _cnpg_
    Synchronize Replicas:
      Enabled:        true
    Update Interval:  30
  Resources:
    Limits:
      Cpu:     4
      Memory:  8Gi
    Requests:
      Cpu:                 4
      Memory:              8Gi
  Smart Shutdown Timeout:  180
  Start Delay:             3600
  Stop Delay:              1800
  Storage:
    Resize In Use Volumes:  true
    Size:                   350Gi
    Storage Class:          pure-k2-cnpg-test
  Switchover Delay:         3600
  Wal Storage:
    Resize In Use Volumes:  true
    Size:                   100Gi
    Storage Class:          pure-k2-cnpg-test
Status:
  Available Architectures:
    Go Arch:  amd64
    Hash:     94527128605ac5100415106fe26c480531d094b3f36626e562a8135f342b89e4
    Go Arch:  arm64
    Hash:     9b7b08592e917ed3b20bb3ae404ea4c0c958bdee73e5411c452d6c464d77f0b4
  Certificates:
    Client CA Secret:  keycloak-ca
    Expirations:
      Keycloak - Ca:           2024-07-17 07:01:23 +0000 UTC
      Keycloak - Replication:  2024-07-17 07:01:23 +0000 UTC
      Keycloak - Server:       2024-07-17 07:01:23 +0000 UTC
    Replication TLS Secret:    keycloak-replication
    Server Alt DNS Names:
      keycloak-rw
      keycloak-rw.cnpg-test
      keycloak-rw.cnpg-test.svc
      keycloak-r
      keycloak-r.cnpg-test
      keycloak-r.cnpg-test.svc
      keycloak-ro
      keycloak-ro.cnpg-test
      keycloak-ro.cnpg-test.svc
    Server CA Secret:             keycloak-ca
    Server TLS Secret:            keycloak-server
  Cloud Native PG Commit Hash:    336ddf53
  Cloud Native PG Operator Hash:  94527128605ac5100415106fe26c480531d094b3f36626e562a8135f342b89e4
  Conditions:
    Last Transition Time:  2024-06-05T13:54:36Z
    Message:               Cluster is Ready
    Reason:                ClusterIsReady
    Status:                True
    Type:                  Ready
    Last Transition Time:  2024-06-05T05:23:00Z
    Message:               Continuous archiving is working
    Reason:                ContinuousArchivingSuccess
    Status:                True
    Type:                  ContinuousArchiving
    Last Transition Time:  2024-06-05T00:00:02Z
    Message:               exit status 1
    Reason:                LastBackupFailed
    Status:                False
    Type:                  LastBackupSucceeded
  Config Map Resource Version:
    Metrics:
      Cnpg - Default - Monitoring:  660594368
  Current Primary:                  keycloak-6
  Current Primary Timestamp:        2024-06-03T23:22:21.161066Z
  First Recoverability Point:       2024-05-27T05:26:57Z
  First Recoverability Point By Method:
    Barman Object Store:  2024-05-27T05:26:57Z
  Healthy PVC:
    keycloak-3
    keycloak-3-wal
    keycloak-5
    keycloak-5-wal
    keycloak-6
    keycloak-6-wal
  Image:  xxx/cnpg:16.2
  Instance Names:
    keycloak-3
    keycloak-5
    keycloak-6
  Instances:  3
  Instances Reported State:
    keycloak-3:
      Is Primary:    false
      Time Line ID:  7
    keycloak-5:
      Is Primary:    false
      Time Line ID:  7
    keycloak-6:
      Is Primary:    true
      Time Line ID:  7
  Instances Status:
    Healthy:
      keycloak-3
      keycloak-5
      keycloak-6
  Last Failed Backup:      2024-06-05T00:28:55Z
  Last Successful Backup:  2024-06-04T02:51:29Z
  Last Successful Backup By Method:
    Barman Object Store:  2024-06-04T02:51:29Z
  Latest Generated Node:  6
  Managed Roles Status:
    By Status:
      Not - Managed:
        app
      Reconciled:
      Reserved:
        postgres
        streaming_replica
    Password Status:
  Phase:                   Cluster in healthy state
  Pooler Integrations:
    Pg Bouncer Integration:
  Pvc Count:        6
  Read Service:     keycloak-r
  Ready Instances:  3
  Secrets Resource Version:
    Application Secret Version:  492750519
    Barman Endpoint CA:          406859735
    Client Ca Secret Version:    646833786
    Managed Role Secret Version:
    Replication Secret Version:         646833788
    Server Ca Secret Version:           646833786
    Server Secret Version:              646833787
  Switch Replica Cluster Status:
  Target Primary:            keycloak-6
  Target Primary Timestamp:  2024-06-04T01:18:13.980624+02:00
  Timeline ID:               7
  Topology:
    Instances:
      keycloak-3:
      keycloak-5:
      keycloak-6:
    Nodes Used:              3
    Successfully Extracted:  true
  Write Service:             keycloak-rw
Events:                      <none>
```

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by mnencia**
When `hot_standby_feedback` is enabled, an inactive replication slot
with `xmin` or `catalog_xmin` set to not NULL, could prevent the
autovacuum on the primary from cleaning the old tuples.
This issue may occur when a former primary rejoins the cluster after
a switchover.

This patch resolves the issue by recreating any HA replication slot on
a standby instance if it has `xmin` or `catalog_xmin` set.

Closes #4802

### CODE REVIEW

File: internal/management/controller/slots/runner/runner.go [hunk 1]
```diff
@@ -177,8 +177,11 @@ func synchronizeReplicationSlots(
 		}
 	}
 	for _, slot := range slotsInLocal.Items {
-		// We delete the slots not present on the primary or old HA replication slots.
-		if !slotsInPrimary.Has(slot.SlotName) || slot.SlotName == mySlotName {
+		// Delete slots on standby with wrong state:
+		//  * slots not present on the primary
+		//  * the slot used by this node
+		//  * slots holding xmin (this can happen on a former primary)
+		if !slotsInPrimary.Has(slot.SlotName) || slot.SlotName == mySlotName || slot.HoldsXmin {
```
Comment (jsilvela) [inline internal/management/controller/slots/runner/runner.go:184]: Want to double check this, because I'm worried that this loop could also run in the primary.
And it could by this logic delete a slot because of having `xmin`.

Comment (jsilvela) [reply internal/management/controller/slots/runner/runner.go:184]: OK, answering my own question.
This loop does not get executed in the primary, but the reason is subtle.
There's
```
func (r *InstanceReconciler) configureSlotReplicator(cluster *apiv1.Cluster) {
	switch r.instance.PodName {
	case cluster.Status.CurrentPrimary, cluster.Status.TargetPrimary:
		r.instance.ConfigureSlotReplicator(nil)
	default:
		r.instance.ConfigureSlotReplicator(cluster.Spec.ReplicationSlots)
	}
}
```
If we changed things, we might inadvertently run the synchronizer in the primary.
Going to see if I think of something.

Comment (mnencia) [reply internal/management/controller/slots/runner/runner.go:184]: The whole slot synchronization subsystem is based on the assumption that it only runs on a non-primary and non-designated-primary instance.

During a promotion, synchronization is stopped for both the former and the new primary.

Even if you imagine a way to force it to run on the primary once, it will result in no changes because the source and destination are equal (so no updates). When a slot has the xmin set, it means it is active, so we will never drop it.

Comment (jsilvela) [reply internal/management/controller/slots/runner/runner.go:184]: > it will result in no changes because the source and destination are equal (so no updates)
This loop `for _, slot := range slotsInLocal.Items` does not check the slots are the same, though.
But, I am reassured that we could not delete an active slot. Thanks for the clarification.

**Review by jsilvela — APPROVED** [review]

**Review by armru — APPROVED** [review]
