### PR TITLE
fix: restore functionality of promote plugin command

### LINKED ISSUE #6475: [Bug]: kubectl plugin command `promote` is not working
### Is there an existing issue already for this bug?

- [x] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [x] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [x] I have read the troubleshooting guide and I think this is a new bug.

### Contact Details

jaime.silvela@enterprisedb.com

### Version

1.25 (latest patch)

### What version of Kubernetes are you using?

1.32

### What is your Kubernetes environment?

Self-managed: kind (evaluation)

### How did you install the operator?

YAML manifest

### What happened?

After creating a simple cluster (cluster-example.yaml ) and waiting for it to be healthy,
and with the newly-compiled kubectl plugin, I run

``` sh
kubectl cnpg promote cluster-example cluster-example-2
```

Right away I get two lines in response

``` sh
{"level":"info","ts":"2024-12-30T15:55:38.989549+01:00","msg":"Cluster is not healthy"}
Node cluster-example-2 in cluster cluster-example will be promoted
```

However nothing happens, and I notice that the TargetPrimary in the cluster status is unchanged.

### Cluster resource

```shell

```

### Relevant log output

```shell
Command output:

{"level":"info","ts":"2024-12-30T15:55:38.989549+01:00","msg":"Cluster is not healthy"}
Node cluster-example-2 in cluster cluster-example will be promoted

Operator logs:

{"level":"debug","ts":"2024-12-30T13:56:47.576467088Z","msg":"Reconciliation loop start","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"079abde6-16ba-4fff-a147-a3eb581db71f","caller":"internal/controller/cluster_controller.go:145"}
{"level":"info","ts":"2024-12-30T13:56:47.694710129Z","msg":"Cluster is healthy","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"079abde6-16ba-4fff-a147-a3eb581db71f"}
{"level":"debug","ts":"2024-12-30T13:56:47.694881921Z","msg":"Reconciliation loop end","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"079abde6-16ba-4fff-a147-a3eb581db71f","caller":"internal/controller/cluster_controller.go:147"}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by jsilvela**
This pull request addresses an issue introduced in the latest plugin release, which rendered the `promote` command ineffective. The patch restores the command functionality and adds a unit test to prevent the issue from happening again.

Closes #6475 

## Release notes

Resolved an issue causing the `promote` plugin command not to work.

### CODE REVIEW

File: pkg/resources/status/phase.go [hunk 1]
```diff
@@ -99,3 +99,59 @@ func RegisterPhaseWithOrigCluster(
 
 	return nil
 }
+
+// RegisterStatusWithOrigCluster updates the status to reflect that in `modifiedCluster`
+// and adjusts the conditions according to whether the Phase is healthy
+func RegisterStatusWithOrigCluster(
+	ctx context.Context,
```
Comment (jsilvela) [inline pkg/resources/status/phase.go:106]: Massive comment here.
I have created a new function because there are several places in the code that rely on
`func RegisterPhaseWithOrigCluster(`
That function now applies only the Phase and PhaseReason, and discards any other information provided via the `modifiedCluster` argument.
Given the comment on that function, not sure this was intended.
If not, then we should fix that one and discard this one.

File: pkg/resources/status/update.go [hunk 2]
```diff
@@ -28,27 +29,33 @@ import (
 )
 
 // PatchWithOptimisticLock updates the status of the cluster using the passed
-// transaction function.
+// transaction functions (in the order passed).
```
Comment (gabriele-wolfox) [inline pkg/resources/status/update.go:32]:
```suggestion
// transaction functions (in the given order).
```

**Review by gabriele-wolfox — APPROVED** [review]

**Review by leonardoce — APPROVED** [review]

**Review by mnencia — APPROVED** [review]

**Comment by aryklein** [comment]
Could you release a patch version with this fix?
Thanks
