### PR TITLE
fix: always use `RegisterPhase` to change the phase

### LINKED ISSUE #4209: [Bug]: "Cluster in healthy state", but ClusterIsNotReady on a newly created instance
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Contact Details

_No response_

### Version

1.22.2

### What version of Kubernetes are you using?

1.29

### What is your Kubernetes environment?

Cloud: Google GKE

### How did you install the operator?

Helm

### What happened?

Newly created cluster reports seemingly impossible status:

```
conditions:
  - lastTransitionTime: 2024-04-04T14:24:53Z
    message: Cluster Is Not Ready
    reason: ClusterIsNotReady
    status: "False"
    type: Ready
  - lastTransitionTime: 2024-04-04T14:25:39Z
    message: Continuous archiving is working
    reason: ContinuousArchivingSuccess
    status: "True"
    type: ContinuousArchiving
phase: Cluster in healthy state
```

Notice how it reports condition `Ready=False`, but phase is `Cluster in healthy state`. Looking at the 1.22.2 `RegisterPhase` it doesn't seem to be possible:

https://github.com/cloudnative-pg/cloudnative-pg/blob/v1.22.2/controllers/cluster_status.go#L718-L737

yet it is what we see in that Cluster resource status.

pod is up and healthy, now errors in the log output of either operator or pod.

### Cluster resource

_No response_

### Relevant log output

cnpg status:

```
Cluster Summary
Name:                mydb-df67
Namespace:           mydb
System ID:           7354017870125015062
PostgreSQL Image:    us.gcr.io/myorg/cnpg-timescale:15.3-2.11.0-1.16.0-r1
Primary instance:    mydb-df67-1
Primary start time:  2024-04-04 14:25:31 +0000 UTC (uptime 1h11m9s)
Status:              Cluster in healthy state 
Instances:           1
Ready instances:     1
Current Write LSN:   1/37A8 (Timeline: 1 - WAL File: 000000010000000100000000)

Certificates Status
Certificate Name                  Expiration Date                Days Left Until Expiration
----------------                  ---------------                --------------------------
mydb-df67-ca           2024-07-03 14:19:53 +0000 UTC  89.95
mydb-df67-replication  2024-07-03 14:19:53 +0000 UTC  89.95
mydb-df67-server       2024-07-03 14:19:53 +0000 UTC  89.95

Continuous Backup status
First Point of Recoverability:  Not Available
Working WAL archiving:          OK
WALs waiting to be archived:    0
Last Archived WAL:              00000001000000000000000F   @   2024-04-04T15:35:49.009011Z
Last Failed WAL:                -

Physical backups
No running physical backups found

Streaming Replication status
Not configured

Unmanaged Replication Slot Status
No unmanaged replication slots found

Managed roles status
No roles managed

Tablespaces status
No managed tablespaces

Instances status
Name                    Database Size  Current LSN  Replication role  Status  QoS         Manager Version  Node
----                    -------------  -----------  ----------------  ------  ---         ---------------  ----
mydb-df67-1  39 MB          1/37A8       Primary           OK      Guaranteed  1.22.2           gke-node-x
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by armru**
This patch aims to solve some rare cases in which the cluster phase and cluster readiness conditions are out of sync.

This can happen because in some parts of the code, we still directly set the phase instead of passing through the dedicated function `RegisterPhase`; this patch aims to solve that.

Closes #4209

### CODE REVIEW

**Comment by armru** [comment]
This is an high risk patch and should be tested and merged only when we are confident that it works and doesn't break existing cluster

File: internal/management/controller/instance_controller.go [hunk 1]
```diff
@@ -313,10 +314,14 @@ func (r *InstanceReconciler) restartPrimaryInplaceIfRequested(
...
-		cluster.Status.PhaseReason = "Primary instance restarted in-place"
-		return true, r.client.Status().Patch(ctx, cluster, client.MergeFrom(oldCluster))
+
+		return true, clusterstatus.RegisterPhase(
+			ctx,
+			r.client,
+			cluster,
+			apiv1.PhaseHealthy,
+			"Primary instance restarted in-place",
+		)
```
Comment (mnencia) [inline internal/management/controller/instance_controller.go:324]: I have been wondering why this piece of code doesn't generate a conflict.
I discovered that both the operator and the instance manager identify themselves as "manager" in the ManagedFields. 
If we ever change this behavior in the future, the code here will trigger a conflict.

**Review by mnencia — APPROVED** [review]

**Review by leonardoce — APPROVED** [review]
