### PR TITLE
fix: increase the timeout for the failover/switchover tests

### LINKED ISSUE #4447: [Bug]: fast failover tests it's consistently and randomly failing
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Contact Details

_No response_

### Version

1.23.0

### What version of Kubernetes are you using?

1.30 (unsuppprted)

### What is your Kubernetes environment?

Self-managed: kind (evaluation)

### How did you install the operator?

YAML manifest

### What happened?

Running into many situations the tests fails with a timeout meaning that it wasn't able to manage and handle the switchover in time

### Cluster resource

_No response_

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by sxd**
Since we know that we have a gap of 127 seconds max, between the connection
is dead and recreated on a second pod that needs to reattach, we should increase
the default timeout on any platform test that it's not local, this doesn't happens on KinD

Closes #4447

### CODE REVIEW

File: tests/e2e/fastfailover_test.go [hunk 1]
```diff
@@ -44,26 +44,14 @@ var _ = Describe("Fast failover", Serial, Label(tests.LabelPerformance, tests.La
...
 
-		// GKE has a higher kube-proxy timeout, and the connections could try
-		// using a service, for which the routing table hasn't changed, getting
-		// stuck for a while.
-		// We raise the timeout, since we can't intervene on GKE configuration.
-		if IsGKE() {
+		// Due to the tcp_syn_retries having a default of 6, meaning that every connection
+		// will retry on a syn after 127 seconds, this will sometimes, delay the reconnection
+		// of the second instance waiting for a connection to be dead, this is specially happening
+		// on platforms like EKS, AKS, GKE and OpenShift
```
Comment (fcanovai) [inline tests/e2e/fastfailover_test.go:51]:
```suggestion
		// The walreceiver of a standby that wasn't promoted may try to reconnect
		// before the rw service endpoints are updated. In this case, the walreceiver
		// can be stuck for waiting for the connection to be established for a time that
		// depends on the tcp_syn_retries sysctl. Since by default
		// net.ipv4.tcp_syn_retries=6, PostgreSQL can wait 2^7-1=127 seconds before
		// restarting the walreceiver.
```

File: tests/e2e/fastswitchover_test.go [hunk 2]
```diff
@@ -210,11 +210,11 @@ func assertFastSwitchover(namespace, sampleFile, clusterName, webTestFile, webTe
...
 
-	// GKE has an higher kube-proxy timeout, and the connections could try
-	// using a service for which the routing table hasn't changed, getting
-	// stuck for a while. We raise the timeout, since we can't intervene
-	// on GKE configuration.
-	if IsGKE() {
+	// Due to the tcp_syn_retries having a default of 6, meaning that every connection
+	// will retry on a syn after 127 seconds, this will sometimes, delay the reconnection
+	// of the second instance waiting for a connection to be dead, this is specially happening
+	// on platforms like EKS, AKS, GKE and OpenShift
```
Comment (fcanovai) [inline tests/e2e/fastswitchover_test.go:216]:
```suggestion
		// The walreceiver of a standby that wasn't promoted may try to reconnect
		// before the rw service endpoints are updated. In this case, the walreceiver
		// can be stuck for waiting for the connection to be established for a time that
		// depends on the tcp_syn_retries sysctl. Since by default
		// net.ipv4.tcp_syn_retries=6, PostgreSQL can wait 2^7-1=127 seconds before
		// restarting the walreceiver.
```

**Review by fcanovai — APPROVED** [review]

**Review by leonardoce — APPROVED** [review]
