### PR TITLE
fix(pooler): do not reconcile resouces that aren't owned

### LINKED ISSUE #4964: [Bug]: creating a pooler with the same name as the cluster internal service breaks the cluster
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Contact Details

abhishek.becs@gmail.com

### Version

1.23.2

### What version of Kubernetes are you using?

1.29

### What is your Kubernetes environment?

Self-managed: kind (evaluation)

### How did you install the operator?

YAML manifest

### What happened?

I deployed CNPG on a kind cluster and created a Postgres cluster using https://cloudnative-pg.io/documentation/1.23/samples/cluster-example.yaml I noticed that the `cluster-example-rw` service has targetPort set to 5432. I then deployed a Pooler with the name set to `cluster-example-rw`. I then noticed that the `cluster-example-rw` service has targetPort set to pgbouncer. The endpoints vanish from from that service. This breaks replication and connectivity.

### Cluster resource

```shell
╰─$ kubectl get cluster cluster-example -o yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"postgresql.cnpg.io/v1","kind":"Cluster","metadata":{"annotations":{},"name":"cluster-example","namespace":"default"},"spec":{"instances":3,"primaryUpdateStrategy":"unsupervised","storage":{"size":"1Gi"}}}
  creationTimestamp: "2024-06-26T21:19:54Z"
  generation: 1
  name: cluster-example
  namespace: default
  resourceVersion: "3495036"
  uid: fd1763ee-7129-4c86-88c5-f674654674c7
spec:
  affinity:
    podAntiAffinityType: preferred
  bootstrap:
    initdb:
      database: app
      encoding: UTF8
      localeCType: C
      localeCollate: C
      owner: app
  enablePDB: true
  enableSuperuserAccess: false
  failoverDelay: 0
  imageName: ghcr.io/cloudnative-pg/postgresql:16.3
  instances: 3
  logLevel: info
  maxSyncReplicas: 0
  minSyncReplicas: 0
  monitoring:
    customQueriesConfigMap:
    - key: queries
      name: cnpg-default-monitoring
    disableDefaultQueries: false
    enablePodMonitor: false
  postgresGID: 26
  postgresUID: 26
  postgresql:
    parameters:
      archive_mode: "on"
      archive_timeout: 5min
      dynamic_shared_memory_type: posix
      log_destination: csvlog
      log_directory: /controller/log
      log_filename: postgres
      log_rotation_age: "0"
      log_rotation_size: "0"
      log_truncate_on_rotation: "false"
      logging_collector: "on"
      max_parallel_workers: "32"
      max_replication_slots: "32"
      max_worker_processes: "32"
      shared_memory_type: mmap
      shared_preload_libraries: ""
      ssl_max_protocol_version: TLSv1.3
      ssl_min_protocol_version: TLSv1.3
      wal_keep_size: 512MB
      wal_level: logical
      wal_log_hints: "on"
      wal_receiver_timeout: 5s
      wal_sender_timeout: 5s
    syncReplicaElectionConstraint:
      enabled: false
  primaryUpdateMethod: restart
  primaryUpdateStrategy: unsupervised
  replicationSlots:
    highAvailability:
      enabled: true
      slotPrefix: _cnpg_
    synchronizeReplicas:
      enabled: true
    updateInterval: 30
  resources: {}
  smartShutdownTimeout: 180
  startDelay: 3600
  stopDelay: 1800
  storage:
    resizeInUseVolumes: true
    size: 1Gi
  switchoverDelay: 3600
status:
  availableArchitectures:
  - goArch: amd64
    hash: e43340cd2ccfa2a8120cf5de6035fe4b18d799bb2feabf99a91434dd9ba92e4c
  - goArch: arm64
    hash: f453a8cb50a418ff9cac24c818b9e155b80487b4152444e48d187161ecdfc0eb
  certificates:
    clientCASecret: cluster-example-ca
    expirations:
      cluster-example-ca: 2024-09-24 21:14:54 +0000 UTC
      cluster-example-replication: 2024-09-24 21:14:54 +0000 UTC
      cluster-example-server: 2024-09-24 21:14:54 +0000 UTC
    replicationTLSSecret: cluster-example-replication
    serverAltDNSNames:
    - cluster-example-rw
    - cluster-example-rw.default
    - cluster-example-rw.default.svc
    - cluster-example-r
    - cluster-example-r.default
    - cluster-example-r.default.svc
    - cluster-example-ro
    - cluster-example-ro.default
    - cluster-example-ro.default.svc
    serverCASecret: cluster-example-ca
    serverTLSSecret: cluster-example-server
  cloudNativePGCommitHash: 4bef8412
  cloudNativePGOperatorHash: f453a8cb50a418ff9cac24c818b9e155b80487b4152444e48d187161ecdfc0eb
  conditions:
  - lastTransitionTime: "2024-06-26T21:21:01Z"
    message: Cluster is Ready
    reason: ClusterIsReady
    status: "True"
    type: Ready
  - lastTransitionTime: "2024-06-26T21:20:12Z"
    message: Continuous archiving is working
    reason: ContinuousArchivingSuccess
    status: "True"
    type: ContinuousArchiving
  configMapResourceVersion:
    metrics:
      cnpg-default-monitoring: "3476288"
  currentPrimary: cluster-example-1
  currentPrimaryTimestamp: "2024-06-26T21:20:12.009147Z"
  healthyPVC:
  - cluster-example-1
  - cluster-example-2
  - cluster-example-3
  image: ghcr.io/cloudnative-pg/postgresql:16.3
  instanceNames:
  - cluster-example-1
  - cluster-example-2
  - cluster-example-3
  instances: 3
  instancesReportedState:
    cluster-example-1:
      isPrimary: true
      timeLineID: 1
    cluster-example-2:
      isPrimary: false
      timeLineID: 1
    cluster-example-3:
      isPrimary: false
      timeLineID: 1
  instancesStatus:
    healthy:
    - cluster-example-1
    - cluster-example-2
    - cluster-example-3
  latestGeneratedNode: 3
  managedRolesStatus: {}
  phase: Cluster in healthy state
  poolerIntegrations:
    pgBouncerIntegration:
      secrets:
      - cluster-example-pooler
  pvcCount: 3
  readService: cluster-example-r
  readyInstances: 3
  secretsResourceVersion:
    applicationSecretVersion: "3476260"
    clientCaSecretVersion: "3476257"
    replicationSecretVersion: "3476259"
    serverCaSecretVersion: "3476257"
    serverSecretVersion: "3476258"
  switchReplicaClusterStatus: {}
  targetPrimary: cluster-example-1
  targetPrimaryTimestamp: "2024-06-26T21:19:54.801307Z"
  timelineID: 1
  topology:
    instances:
      cluster-example-1: {}
      cluster-example-2: {}
      cluster-example-3: {}
    nodesUsed: 1
    successfullyExtracted: true
  writeService: cluster-example-rw
```

```
╰─$ kubectl get pooler cluster-example-rw -o yaml
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"postgresql.cnpg.io/v1","kind":"Pooler","metadata":{"annotations":{},"name":"cluster-example-rw","namespace":"default"},"spec":{"cluster":{"name":"cluster-example"},"instances":3,"pgbouncer":{"parameters":{"default_pool_size":"10","max_client_conn":"1000"},"poolMode":"session"},"type":"rw"}}
  creationTimestamp: "2024-06-27T03:30:08Z"
  generation: 1
  name: cluster-example-rw
  namespace: default
  resourceVersion: "3495047"
  uid: 44b76360-89a9-4737-a215-0be53c9ae13a
spec:
  cluster:
    name: cluster-example
  instances: 3
  pgbouncer:
    parameters:
      default_pool_size: "10"
      max_client_conn: "1000"
    paused: false
    poolMode: session
  type: rw
status:
  instances: 3
  secrets:
    clientCA:
      name: cluster-example-ca
      version: "3476257"
    pgBouncerSecrets:
      authQuery:
        name: cluster-example-pooler
        version: "3476792"
    serverCA:
      name: cluster-example-ca
      version: "3476257"
    serverTLS:
      name: cluster-example-server
      version: "3476258"
```
```


### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by armru**
This patch ensures that we don't reconcile an expected managed resource if we don't find the proper ownership metadata.

Closes #4964

### CODE REVIEW

**Comment by achanda** [comment]
Can we add some negative tests here? Maybe check that a resource is not reconciled if not owned by the pooler

**Review by mnencia — APPROVED** [review]

File: internal/controller/pooler_controller.go [hunk 1]
```diff
@@ -156,6 +161,56 @@ func isOwnedByPooler(obj client.Object) (string, bool) {
 	return owner.Name, true
 }
 
+func isOwnedByPooler(poolerName string, obj client.Object) bool {
+	ownerName, isOwned := isOwnedByPoolerKind(obj)
```
Comment (gabriele-wolfox) [inline internal/controller/pooler_controller.go:165]: If you agree, I would refactor
`if !isOwned {
		return false
	}
	return poolerName == ownerName`
	
with one liner

`return isOwned && poolerName == ownerName`

**Comment by litaocdl** [comment]
e2e run here https://github.com/EnterpriseDB/cloudnative-pg/actions/runs/9754285995

**Comment by achanda** [comment]
Don't we also need to change the name of the default service generated by the pooler? or maybe we can add a webhook check that pooler name and cluster name cannot be the same

**Review by litaocdl — APPROVED** [review]

**Comment by litaocdl** [comment]
> Don't we also need to change the name of the default service generated by the pooler? or maybe we can add a webhook check that pooler name and cluster name cannot be the same

In another feature we could have the cluster service name customized, so for webhook, we could stop the pooler name the same with default rw service name of referenced cluster.

**Comment by mnencia** [comment]
> > Don't we also need to change the name of the default service generated by the pooler? or maybe we can add a webhook check that pooler name and cluster name cannot be the same
> 
> In another feature we could have the cluster service name customized, so for webhook, we could stop the pooler name the same with default rw service name of referenced cluster.

I don't think that we should add a check for the only `<cluster>-rw` service name. This patch solves a structural problem triggered by any existing service (or deployment, or any other object but a ServiceAccount), regardless of whether it is created by the Cluster.
