### PR TITLE
fix: improve error handling in `EnsureDirectoryExists` function

### LINKED ISSUE #4891: [Bug]:  `EnsureDirectoryExists`  always returns nil if error isn't  `the file is not exist`
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Contact Details

huyantian0@gmail.com

### Version

1.23.2

### What version of Kubernetes are you using?

1.30 (unsupported)

### What is your Kubernetes environment?

Self-managed: kind (evaluation)

### How did you install the operator?

YAML manifest

### What happened?

https://github.com/cloudnative-pg/cloudnative-pg/blob/8d0b05a895744443909c0d8522a524a816a39ac2/pkg/fileutils/fileutils.go#L299-L308

 `EnsureDirectoryExists`  always returns nil if error isn't  `the file is not exist` 

### Cluster resource

_No response_

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by YanniHu1996**
This update modifies the `EnsureDirectoryExists` function to propagate previously ignored unexpected errors.
The function also verifies that the target is a directory when it already exists.

Closes #4891

### CODE REVIEW

**Comment by YanniHu1996** [comment]
e2e from fork 
https://github.com/EnterpriseDB/cloudnative-pg/actions/runs/9560725211

**Review by mnencia — APPROVED** [review]

File: pkg/fileutils/fileutils.go [hunk 1]
```diff
@@ -296,15 +296,15 @@ func EnsureParentDirectoryExist(fileName string) error {
 
 // EnsureDirectoryExists check if the passed directory exists or not, and if
 // it doesn't exist, create it using 0700 as permissions bits
-func EnsureDirectoryExists(destinationDir string) error {
-	if _, err := os.Stat(destinationDir); os.IsNotExist(err) {
```
Comment (jsilvela) [inline pkg/fileutils/fileutils.go:300]: while we're modifying this function, I think we should ensure that if the directory exists, it should have the right permissions. Going to try adding tests and modify.

File: pkg/fileutils/fileutils.go [hunk 2]
```diff
@@ -296,15 +296,15 @@ func EnsureParentDirectoryExist(fileName string) error {
...
+func EnsureDirectoryExists(destinationDir string) (err error) {
```
Comment (jsilvela) [inline pkg/fileutils/fileutils.go:299]: while we're modifying this function, I think we should ensure that if the directory exists, it should have the right permissions. Going to try adding tests and modify.

**Comment by jsilvela** [comment]
I added some testing and realized if given an existing dir with the wrong permissions,
the function would do nothing and report success.
Changed that to chmod if it finds wrong permissions.

File: pkg/fileutils/fileutils.go [hunk 3]
```diff
@@ -294,14 +295,18 @@ func EnsureParentDirectoryExist(fileName string) error {
...
-			return err
-		}
+	fileInfo, err := os.Stat(destinationDir)
+	if os.IsNotExist(err) {
+		return os.MkdirAll(destinationDir, 0o700)
+	} else if err != nil {
+		return err
+	}
+	if fileInfo.Mode().Perm() != fs.FileMode(0o700) {
+		return os.Chmod(destinationDir, 0o700) // nolint:gosec
```
Comment (mnencia) [inline pkg/fileutils/fileutils.go:309]: Please don't do that. It could have unintended consequences, and it goes beyond ensuring that the directory exists.

Comment (jsilvela) [reply pkg/fileutils/fileutils.go]: yep, found out the tests were failing. Rolled back.

**Review by jsilvela — APPROVED** [review]

**Comment by jsilvela** [comment]
Green tests https://github.com/EnterpriseDB/cloudnative-pg/actions/runs/9649606706

**Comment by mnencia** [comment]
Full E2E running on EDB fork https://github.com/EnterpriseDB/cloudnative-pg/actions/runs/9659652078
