### PR TITLE
fix: ensures that the promoted standby active connections are dropped after promotion

### LINKED ISSUE #736: ensure we drop all active connections on the standby that is promoted
We should ensure that we drop all the read-only connections after we promote a standby.

### PR DESCRIPTION
**Pull request by armru**
This patch drops all the connections made before the standby promotion are dropped.

Closes #736

Signed-off-by: Armando Ruocco <armando.ruocco@enterprisedb.com>

### CODE REVIEW

**Review by jlong49 — APPROVED** [review]

File: pkg/utils/time.go [hunk 1]
```diff
@@ -27,11 +27,15 @@ import (
...
+	if parsedTimestamp, err := time.Parse(metav1.RFC3339Micro, timestamp); err == nil {
+		return parsedTimestamp.Format("2006-01-02 15:04:05.000000Z07:00")
+	}
+
+	if parsedTimestamp, err := time.Parse(time.RFC3339, timestamp); err == nil {
+		return parsedTimestamp.Format("2006-01-02 15:04:05.000000Z07:00")
 	}
-	return parsedTimestamp.Format("2006-01-02 15:04:05.000000Z07:00")
+
+	return timestamp
```
Comment (mnencia) [inline pkg/utils/time.go:38]: This is a good change, but I do not think it belongs to this patch.

**Review by mnencia — APPROVED** [review]

**Review by jsilvela — APPROVED** [review]
