### PR TITLE
fix: wait for app user secret before starting initdb

### LINKED ISSUE #6069: [Bug]: initdb doesn't wait for secret
### Is there an existing issue already for this bug?

- [x] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [x] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [x] I have read the troubleshooting guide and I think this is a new bug.

### Contact Details

dmills@qumulo.com

### Version

1.24.0

### What version of Kubernetes are you using?

1.30

### What is your Kubernetes environment?

Self-managed: k3s

### How did you install the operator?

Helm

### What happened?

The initdb option to create a new DB doesn't appear to wait for the secret to exist before starting. Then later if the secret is created the owner is not created unless you separately use a role.

We use external-secrets to save secrets in a secure vault, but if we deploy the external-secret and the cluster at the same time they both start working even though external-secrets may have not created the Kubernetes secret. So you end up with a DB that doesn't have a owner can the user cannot connect. If you recreate the cluster once the secret exists everything proceeds normally

### Cluster resource

```shell
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: db
  namespace: dv
spec:
  instances: 2
  storage:
    size: 10Gi
  bootstrap:
    initdb:
      database: db
      owner: db
      secret:
        name: db-secret

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-secret
  namespace: db
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secretstore
    kind: ClusterSecretStore
  target:
    name: db-secret
    template:
      type: kubernetes.io/basic-auth
      data:
        username: "{{ .login }}"
        password: "{{ .password }}"
        host: "{{ .host }}"
  dataFrom:
    - extract:
        key: db-secret
```

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by armru**
The scope of this PR is to address #6069 with minimally invasive changes

Closes #6069

### CODE REVIEW

File: internal/controller/cluster_create.go [hunk 1]
```diff
@@ -1153,6 +1153,20 @@ func (r *ClusterReconciler) createPrimaryInstance(
...
 	default:
+		appSecretName := cluster.GetApplicationSecretName()
+		if appSecretName != "" && cluster.ShouldInitDBCreateApplicationDatabase() {
+			var appSecret corev1.Secret
+			key := client.ObjectKey{Namespace: cluster.Namespace, Name: appSecretName}
+			if err := r.Get(ctx, key, &appSecret); err != nil {
+				if apierrs.IsNotFound(err) {
+					r.Recorder.Eventf(cluster, "Normal", "WaitingForSecret",
+						"Waiting for application secret %s to exist before initdb", appSecretName)
+					return ctrl.Result{RequeueAfter: 10 * time.Second}, nil
```
Comment (armru) [inline internal/controller/cluster_create.go]: we could add a phase but I'm making this minimally invasive

File: pkg/specs/jobs.go [hunk 2]
```diff
@@ -385,6 +386,22 @@ func CreatePrimaryJob(cluster apiv1.Cluster, nodeSerial int, role jobRole, initC
...
+			ValueFrom: &corev1.EnvVarSource{
+				SecretKeyRef: &corev1.SecretKeySelector{
+					LocalObjectReference: corev1.LocalObjectReference{Name: cluster.GetApplicationSecretName()},
+					Key:                  "username",
+					Optional:             ptr.To(false),
+				},
+			},
+		})
+	}
+
```
Comment (armru) [inline pkg/specs/jobs.go:404]: Potentially we could use the container envfrom field to mount the whole secret, but I felt like for what we want to achieve this minimalistic approach that exposes only the username to the job is the best

**Comment by dominik-niebuhr** [comment]
do we have any ETA for a release once this is merged? :) this would help us remove a very ugly workaround

**Review by leonardoce — APPROVED** [review]

**Review by mnencia — APPROVED** [review]

**Comment by dominik-niebuhr** [comment]
@armru Will this fix also work for secrets of managed roles? If not should I open a new issue or do we keep the existing issue open for that?
