### PR TITLE
fix: delay rollout until every Pods received the same configuration

### LINKED ISSUE #6956: [Bug]: double switchover on configuration upgrade
### Is there an existing issue already for this bug?

- [x] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [x] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [x] I have read the troubleshooting guide and I think this is a new bug.

### Contact Details

_No response_

### Version

trunk (main)

### What version of Kubernetes are you using?

1.32

### What is your Kubernetes environment?

Self-managed: kind (evaluation)

### How did you install the operator?

YAML manifest

### What happened?

In a cluster with `PrimaryUpgradeMethod: true`, there is a nonzero probability that an update of a parameter that requires a restart triggers two switchovers, first restarting the primary, and later the newly promoted instance.

This can happen if an event happens after the primary has applied the new configuration while the other instances have not.

### Cluster resource

```shell

```

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by leonardoce**
This patch delays the rollout of Pods to the point where every instance manager received the latest PostgreSQL configuration and applied it.

This prevents the operator from switching over two times to apply the same configuration when the primary received the configuration and, immediately after that, a reconciliation loop has been triggered on the cluster.

Fixes: #6956

# Release notes

```
Prevent a race condition causing the operator to perform two switchovers to update
the PostgreSQL configuration.
```

### CODE REVIEW

**Review by armru — APPROVED** [review]

**Comment by leonardoce** [comment]
https://github.com/EnterpriseDB/cloudnative-pg/actions/runs/13563660081

File: internal/controller/cluster_controller.go [hunk 1]
```diff
@@ -928,6 +929,23 @@ func (r *ClusterReconciler) reconcilePods(
 		return ctrl.Result{RequeueAfter: 1 * time.Second}, ErrNextLoop
 	}
 
+	// Stop acting here if the Pods don't have received
```
Comment (jsilvela) [inline internal/controller/cluster_controller.go:932]:
```suggestion
	// Stop acting here if the Pods haven't received
```

File: internal/controller/cluster_controller.go [hunk 2]
```diff
@@ -928,6 +929,23 @@ func (r *ClusterReconciler) reconcilePods(
...
+	// the latest PostgreSQL configuration.
```
Comment (jsilvela) [inline internal/controller/cluster_controller.go:933]: Actually I think this whole comment is stale. The following code paragraph clarifies we request (stop acting) if there are pods in different configs

File: pkg/management/postgres/probes.go [hunk 3]
```diff
@@ -86,6 +92,30 @@ func (instance *Instance) GetStatus() (result *postgres.PostgresqlStatus, err er
...
+			// and we still didn't load a generated configuration.
+			//
+			// This unfortunately will report an error
+			// into the PostgreSQL logs, but there's no
+			// current way to do it without raising an
+			// error at this moment.
+			//
+			// It should not represent a major issue since
+			// a correct configuration is going to be
+			// loaded immediately.
```
Comment (jsilvela) [inline pkg/management/postgres/probes.go:112]: Here I wonder. So, we set the configuration hash to "", and then when we do `reconcilePods`, we see that not all pods have a hash, so we do a rolling upgrade, and this could repeat?

**Comment by jsilvela** [comment]
https://github.com/EnterpriseDB/cloudnative-pg/actions/runs/13678905930

**Review by jsilvela — APPROVED** [review]

**Review by mnencia — APPROVED** [review]
