### PR TITLE
fix: add AppArmor only when the matching container is present

### LINKED ISSUE #2489: AppArmor annotations are not added correctly
I was trying to follow the guide on https://cloudnative-pg.io/documentation/1.20/security/#restricting-pod-access-using-apparmor but when I add all the suggested annotations in the cluster spec

```
    kind: Cluster
    metadata:
        name: cluster-apparmor
        annotations:
            container.apparmor.security.beta.kubernetes.io/postgres: runtime/default
            container.apparmor.security.beta.kubernetes.io/initdb: runtime/default
            container.apparmor.security.beta.kubernetes.io/join: runtime/default
```

the K8s API server rejected the following operator reconciliation by saying:

```
2023-07-24T15:22:54.119717065Z {"level":"info","ts":"2023-07-24T15:22:54Z","msg":"Updating cluster annotations on pod","controller":"cluster","controllerGroup":"clusters.postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"<CLUSTER_NAME>","namespace":"default"},"namespace":"default","name":"<CLUSTER_NAME>","reconcileID":"f75dc435-2470-4411-88c1-6d92a0cd4a60","uuid":"f5bb21bf-2a35-11ee-a2bb-be362929010f","pod":"<CLUSTER_NAME>-1"}
2023-07-24T15:22:54.139177879Z {"level":"error","ts":"2023-07-24T15:22:54Z","msg":"while patching instance metadata","controller":"cluster","controllerGroup":"clusters.postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"<CLUSTER_NAME>","namespace":"default"},"namespace":"default","name":"<CLUSTER_NAME>","reconcileID":"f75dc435-2470-4411-88c1-6d92a0cd4a60","uuid":"f5bb21bf-2a35-11ee-a2bb-be362929010f","instanceName":"<CLUSTER_NAME>-1","error":"Pod \"<CLUSTER_NAME>-1\" is invalid: [metadata.annotations[container.apparmor.security.beta.kubernetes.io/initdb]: Invalid value: \"initdb\": container not found, metadata.annotations[container.apparmor.security.beta.kubernetes.io/join]: Invalid value: \"join\": container not found, metadata.annotations[container.apparmor.security.beta.kubernetes.io/postgres]: Forbidden: may not add AppArmor annotations, metadata.annotations[container.apparmor.security.beta.kubernetes.io/join]: Forbidden: may not add AppArmor annotations, metadata.annotations[container.apparmor.security.beta.kubernetes.io/initdb]: Forbidden: may not add AppArmor annotations]","stacktrace":"github.com/cloudnative-pg/cloudnative-pg/pkg/management/log.(*logger).Error\n\tcloudnative-pg/pkg/management/log/log.go:128\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/reconciler/instance.ReconcileMetadata\n\tcloudnative-pg/pkg/reconciler/instance/metadata.go:63\ngithub.com/cloudnative-pg/cloudnative-pg/controllers.(*ClusterReconciler).reconcile\n\tcloudnative-pg/controllers/cluster_controller.go:262\ngithub.com/cloudnative-pg/cloudnative-pg/controllers.(*ClusterReconciler).Reconcile\n\tcloudnative-pg/controllers/cluster_controller.go:148\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\tcloudnative-pg/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:118\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tcloudnative-pg/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:314\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tcloudnative-pg/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:265\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tcloudnative-pg/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:226"}
2023-07-24T15:22:54.139493081Z {"level":"error","ts":"2023-07-24T15:22:54Z","msg":"Reconciler error","controller":"cluster","controllerGroup":"clusters.postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"<CLUSTER_NAME>","namespace":"default"},"namespace":"default","name":"<CLUSTER_NAME>","reconcileID":"f75dc435-2470-4411-88c1-6d92a0cd4a60","error":"cannot updated metadata on pods: Pod \"<CLUSTER_NAME>-1\" is invalid: [metadata.annotations[container.apparmor.security.beta.kubernetes.io/initdb]: Invalid value: \"initdb\": container not found, metadata.annotations[container.apparmor.security.beta.kubernetes.io/join]: Invalid value: \"join\": container not found, metadata.annotations[container.apparmor.security.beta.kubernetes.io/postgres]: Forbidden: may not add AppArmor annotations, metadata.annotations[container.apparmor.security.beta.kubernetes.io/join]: Forbidden: may not add AppArmor annotations, metadata.annotations[container.apparmor.security.beta.kubernetes.io/initdb]: Forbidden: may not add AppArmor annotations]","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tcloudnative-pg/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:324\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tcloudnative-pg/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:265\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tcloudnative-pg/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:226"}
``` 

Can we add into CloudNativePG some way to pass only the first part of this AppArmor annotation, that is `container.apparmor.security.beta.kubernetes.io`, and then let the operator correctly set only the needed ones every time it creates a new cluster Pod by setting exactly the Container Names that it contains?

This has been tested on Azure AKS running

```
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.6", GitCommit:"94c50547e633f1db5d4c56b2b305670e14987d59", GitTreeState:"clean", BuildDate:"2023-06-12T18:46:30Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
```

### PR DESCRIPTION
**Pull request by armru**
Closes #2489

### CODE REVIEW

File: pkg/reconciler/persistentvolumeclaim/metadata.go [hunk 1]
```diff
@@ -150,8 +150,7 @@ func newAnnotationReconciler(cluster *apiv1.Cluster) metadataReconciler {
 			return utils.IsAnnotationSubset(pvc.Annotations,
 				cluster.Annotations,
 				cluster.GetFixedInheritedAnnotations(),
-				configuration.Current) &&
```
Comment (armru) [inline pkg/reconciler/persistentvolumeclaim/metadata.go:153]: we were checking for appArmor in the PVC reconciliation, I removed it because it made no sense.

We didn't add appArmor annotations anyway

**Review by mnencia — APPROVED** [review]

**Comment by mnencia** [comment]
/ok-to-merge E2E tests failed for a PVC allocation glitch

**Review by litaocdl — APPROVED** [review]
