### PR TITLE
fix(hibernate): evaluate `pg_ctl status` exit code to determine if an instance is running

### LINKED ISSUE #934: improve how we determine if an instance is stopped during hibernate on
Right now during hibernation, we determine if an instance is stopped by doing a string match on pg_ctl: no server running but this could be not always true given that is dependant on the Postgres locale set.

We should improve the logic by relying on exit codes instead.

### PR DESCRIPTION
**Pull request by armru**
This patch ensures that we rely only on the exit code to determine if an instance is stopped. 

This removes the previous behavior of checking the pg_ctl message which generated errors with languages different than English

Closes #934

Signed-off-by: Armando Ruocco <armando.ruocco@enterprisedb.com>

### CODE REVIEW

File: internal/plugin/resources/instance.go [hunk 1]
```diff
@@ -163,3 +173,35 @@ func getPVC(ctx context.Context, name string) (*v1.PersistentVolumeClaim, error)
...
+	timeout := time.Second * 2
+	clientInterface := kubernetes.NewForConfigOrDie(plugin.Config)
+	stdout, _, err := utils.ExecCommand(
+		ctx,
+		clientInterface,
+		plugin.Config,
+		pod,
+		specs.PostgresContainerName,
+		&timeout,
+		"/bin/bash", "-c", "pg_ctl status &>/dev/null; echo $?")
```
Comment (mnencia) [inline internal/plugin/resources/instance.go:191]:
```suggestion
		"/bin/sh", "-c", "pg_ctl status >/dev/null 2>&1; echo $?")
```

Comment (mnencia) [reply internal/plugin/resources/instance.go:191]: better, we are ignoring stderr anyway, so just remove the stderr redirection...

**Comment by armru** [comment]
take extra care in not squashing

**Review by leonardoce — APPROVED** [review]
