### PR TITLE
fix: do not patch when object doesn't change

### LINKED ISSUE #4301: [Bug]: Operatorclient should not patch on Delete()
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Contact Details

_No response_

### Version

1.22.2

### What version of Kubernetes are you using?

1.29

### What is your Kubernetes environment?

Self-managed: kind (evaluation)

### How did you install the operator?

YAML manifest

### What happened?

Currently, we use the interface client to run some operations like delete an object, and this interface with the new CNPG-I will try to patch that object, even if the object doesn't change and therefore will try to patch an object in deleting process and is not there anymore

### Cluster resource

_No response_

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by sxd**
Previously we were patching the object even if this didn't change, this was triggering a patch over an object that was already patched and deleted.

Closes #4301

### CODE REVIEW

**Review by armru — APPROVED** [review]

File: internal/cnpi/plugin/operatorclient/client.go [hunk 1]
```diff
@@ -97,10 +99,13 @@ func (e *extendedClient) Delete(
...
-		contextLogger.Error(err, "while patching before delete")
-		return err
+	if !reflect.DeepEqual(origObj, obj) {
+		if err := e.Client.Patch(ctx, obj, client.MergeFrom(origObj)); err != nil && !apierrors.IsNotFound(err) {
+			contextLogger.Error(err, "while patching before delete")
+			return err
+		}
 	}
+
 	return e.Client.Delete(ctx, obj, opts...)
```
Comment (armru) [inline internal/cnpi/plugin/operatorclient/client.go:109]: Currently, it could happen that we execute a delete that we know doesn't exist anymore. IMO, this is fine, given that we preserve the original behavior of invoking a Delete with the runtime client.

**Review by armru — APPROVED** [review]

**Comment by leonardoce** [comment]
LGTM. E2e: https://github.com/EnterpriseDB/cloudnative-pg/actions/runs/8722071272

**Comment by armru** [comment]
I think we should not backport this? @leonardoce

**Comment by leonardoce** [comment]
> I think we should not backport this? @leonardoce

Yeah, no backport for this PR

**Comment by leonardoce** [comment]
The E2e tests were failing because of #4330.
I'm starting new ones:

https://github.com/EnterpriseDB/cloudnative-pg/actions/runs/8739338477

**Comment by leonardoce** [comment]
WOW! E2e tests are totally green! Merging this.

**Review by leonardoce — APPROVED** [review]
