### PR TITLE
fix(backup,online): fail backup if targetPod becomes unhealthy

### LINKED ISSUE #7905: [Bug]: Backup remains running after target pod is killed
### Is there an existing issue already for this bug?

- [x] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [x] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [x] I have read the troubleshooting guide and I think this is a new bug.

### Contact Details

agelwarg@galileosuite.com

### Version

1.26 (latest patch)

### What version of Kubernetes are you using?

1.31

### What is your Kubernetes environment?

Self-managed: kind (evaluation)

### How did you install the operator?

Helm

### What happened?

When a backup is running and the target pod is terminated/killed, the backup status appears to remain `running` indefinitely.  In our case, it looks like the pod was terminated because it exhausted the ephemeral-storage limit, but I don't think that part is particularly relevant.   I would expect the same if you simply delete the pod while the backup is in progress.

### Cluster resource

```shell
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: test-database
spec:
  instances: 1
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ImageCatalog
    name: test
    major: 17
  primaryUpdateMethod: switchover
  bootstrap:
    initdb:
      database: 'test'
      owner: 'test'
  backup:
    retentionPolicy: 3d
    barmanObjectStore:
      destinationPath: "s3://some-bucket/database"
      s3Credentials:
        inheritFromIAMRole: true
      data:
        compression: "snappy"
  storage:
    size: 50Gi
    storageClass: gp3-encrypted
```

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by armru**
This patch ensures that the backup process is immediately aborted if the targetPod becomes unhealthy during an online backup operation. Previously, the backup would continue even if the target instance was no longer in a healthy state, potentially resulting in incomplete or inconsistent backups. By monitoring the pod's health status, the process now fails fast, providing early feedback and increasing the accuracy of the Backup object status.

Related #7503
Closes #7905

### Release notes

```
Online backup operation now fails immediately if the targetPod becomes
unhealthy, increasing the accuracy of the Backup object status.
```

### CODE REVIEW

File: internal/controller/backup_controller.go [hunk 1]
```diff
@@ -65,6 +66,11 @@ const backupPhase = ".status.phase"
 // where the name of the cluster is written
 const clusterName = ".spec.cluster.name"
 
+// isRunningResult ensures that we periodically check running backups. It could happen that the targetPod is destroyed
+// or stops responding.
+// This should be used almost always when a backup is running
+var isRunningResult = ctrl.Result{RequeueAfter: 10 * time.Minute}
```
Comment (uhthomas) [inline internal/controller/backup_controller.go]: It would probably be better to have the requeue duration as a const than this global variable.

```suggestion
const isRunningRequeueDuration = 10 * time.Minute
```

```go
return ctrl.Result{RequeueAfter: isRunningRequeueDuration}
```

Comment (armru) [reply internal/controller/backup_controller.go]: What if we add a function that creates the result? Something on the line: getBackupRunningResult() 
This would:
- remove the need of a global variable
- returns always the same object (the global variable could be conceptually modified)
- The object would be ready to be used!

Comment (leonardoce) [reply internal/controller/backup_controller.go]: Yep, that's what I did

**Review by leonardoce — APPROVED** [review]

**Review by NiccoloFei — APPROVED** [review]

**Review by mnencia — APPROVED** [review]
