### PR TITLE
fix(upgrades): consider previous controldata when creating the new datadir

### LINKED ISSUE #7273: [Bug]: "old and new pg_controldata WAL segment sizes are invalid or do not match"
### Is there an existing issue already for this bug?

- [x] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [x] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [x] I have read the troubleshooting guide and I think this is a new bug.

### Contact Details

_No response_

### Version

trunk (main)

### What version of Kubernetes are you using?

1.32

### What is your Kubernetes environment?

Self-managed: kind (evaluation)

### How did you install the operator?

YAML manifest

### What happened?

I have created a Postgres 13 cluster and requested data checksums and a different segment size. The major upgrade process fails with the following error:

```
old and new pg_controldata WAL segment sizes are invalid or do not match
```

To replicate it, use the RC1 version, create the cluster with version 13 then once it is up change 13 with 17.

### Cluster resource

```shell
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:13-minimal-bullseye
  instances: 3

  storage:
    size: 1Gi
  walStorage:
    size: 1Gi
  bootstrap:
    initdb:
      dataChecksums: true
      walSegmentSize: 64
```

### Relevant log output

```shell
pg-1-major-upgrade-6g5cg major-upgrade {"level":"info","ts":"2025-04-01T14:40:52.696911223Z","logger":"pg_upgrade","msg":"Checking cluster versions                                     ok","pipe":"stdout","logging_pod":"pg-1-major-upgrade"}
pg-1-major-upgrade-6g5cg major-upgrade {"level":"info","ts":"2025-04-01T14:40:52.702945202Z","logger":"pg_upgrade","msg":"old and new pg_controldata WAL segment sizes are invalid or do not match","pipe":"stdout","logging_pod":"pg-1-major-upgrade"}
pg-1-major-upgrade-6g5cg major-upgrade {"level":"info","ts":"2025-04-01T14:40:52.702964575Z","logger":"pg_upgrade","msg":"Failure, exiting","pipe":"stdout","logging_pod":"pg-1-major-upgrade"}
pg-1-major-upgrade-6g5cg major-upgrade Error: error while running pg_upgrade: error while running "/usr/lib/postgresql/17/bin/pg_upgrade --link --username postgres --old-bindir /controller/old/usr/lib/postgresql/16/bin --old-datadir /var/lib/postgresql/data/pgdata --new-datadir /var/lib/postgresql/data/pgdata-new": exit status 1
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### LINKED ISSUE #7276: [Bug]: major-upgrade fails with "old cluster uses data checksums but the new one does not"
### Is there an existing issue already for this bug?

- [x] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [x] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [x] I have read the troubleshooting guide and I think this is a new bug.

### Contact Details

_No response_

### Version

1.25 (latest patch)

### What version of Kubernetes are you using?

other (unsupported)

### What is your Kubernetes environment?

Other

### How did you install the operator?

YAML manifest

### What happened?

upgrading does not work with `datachecksums: true`

### Cluster resource

```shell
imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql
#    major: 16
    major: 17
...
    initdb:
      database: app
      encoding: UTF8
      dataChecksums: true
...
```

### Relevant log output

```shell
│ netchb-1-major-upgrade-rtc8s major-upgrade {"level":"info","ts":"2025-04-02T08:04:46.390405028Z","logger":"initdb","msg":"Success. You can now start the database server using:","pipe":"stdout","logging_pod":"netchb-1-major-upgrade"}                                               │
│ netchb-1-major-upgrade-rtc8s major-upgrade {"level":"info","ts":"2025-04-02T08:04:46.390415853Z","logger":"initdb","msg":"    pg_ctl -D /var/lib/postgresql/data/pgdata-new -l logfile start","pipe":"stdout","logging_pod":"netchb-1-major-upgrade"}                                  │
│ netchb-1-major-upgrade-rtc8s major-upgrade {"level":"info","ts":"2025-04-02T08:04:46.391325812Z","msg":"Preparing configuration files","logging_pod":"netchb-1-major-upgrade","directory":"/var/lib/postgresql/data/pgdata-new"}                                                       │
│ netchb-1-major-upgrade-rtc8s major-upgrade {"level":"info","ts":"2025-04-02T08:04:46.396838217Z","msg":"Installed configuration file","logging_pod":"netchb-1-major-upgrade","pgdata":"/var/lib/postgresql/data/pgdata-new","filename":"custom.conf"}                                  │
│ netchb-1-major-upgrade-rtc8s major-upgrade {"level":"info","ts":"2025-04-02T08:04:46.399181051Z","msg":"Installed configuration file","logging_pod":"netchb-1-major-upgrade","pgdata":"/var/lib/postgresql/data/pgdata-new","filename":"pg_ident.conf"}                                │
│ netchb-1-major-upgrade-rtc8s major-upgrade {"level":"info","ts":"2025-04-02T08:04:46.399231376Z","msg":"Checking if we have anything to update","logging_pod":"netchb-1-major-upgrade"}                                                                                                │
│ netchb-1-major-upgrade-rtc8s major-upgrade {"level":"info","ts":"2025-04-02T08:04:46.400205665Z","msg":"Running pg_upgrade","logging_pod":"netchb-1-major-upgrade"}                                                                                                                    │
│ netchb-1-major-upgrade-rtc8s major-upgrade {"level":"info","ts":"2025-04-02T08:04:46.511856037Z","logger":"pg_upgrade","msg":"Performing Consistency Checks","pipe":"stdout","logging_pod":"netchb-1-major-upgrade"}                                                                   │
│ netchb-1-major-upgrade-rtc8s major-upgrade {"level":"info","ts":"2025-04-02T08:04:46.511876693Z","logger":"pg_upgrade","msg":"-----------------------------","pipe":"stdout","logging_pod":"netchb-1-major-upgrade"}                                                                   │
│ netchb-1-major-upgrade-rtc8s major-upgrade {"level":"info","ts":"2025-04-02T08:04:46.511892737Z","logger":"pg_upgrade","msg":"Checking cluster versions                                     ok","pipe":"stdout","logging_pod":"netchb-1-major-upgrade"}                                │
│ netchb-1-major-upgrade-rtc8s major-upgrade {"level":"info","ts":"2025-04-02T08:04:46.524426679Z","logger":"pg_upgrade","msg":"old cluster uses data checksums but the new one does not","pipe":"stdout","logging_pod":"netchb-1-major-upgrade"}                                        │
│ netchb-1-major-upgrade-rtc8s major-upgrade {"level":"info","ts":"2025-04-02T08:04:46.524450118Z","logger":"pg_upgrade","msg":"Failure, exiting","pipe":"stdout","logging_pod":"netchb-1-major-upgrade"}                                                                                │
│ netchb-1-major-upgrade-rtc8s major-upgrade Error: error while running pg_upgrade: error while running "/usr/lib/postgresql/17/bin/pg_upgrade --link --username postgres --old-bindir /controller/old/usr/lib/postgresql/16/bin --old-datadir /var/lib/postgresql/data/pgdata --new-dat │
│ adir /var/lib/postgresql/data/pgdata-new": exit status 1                                                                                                                                                                                                                               │
│ stream closed EOF for cnpg-system/netchb-1-major-upgrade-rtc8s (major-upgrade)
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by mnencia**
Closes #7273 #7276

### CODE REVIEW

File: internal/cmd/manager/instance/upgrade/execute/cmd.go [hunk 1]
```diff
@@ -277,6 +299,31 @@ func runInitDB(destDir string, walDir *string) error {
...
+
+	// Extract the dat checksum version from the pg_controldata output
+	dataPageChecksumVersion, ok := pgControlData[utils.PgControlDataDataPageChecksumVersion]
+	if !ok {
+		return fmt.Errorf("no '%s' section into pg_controldata output", utils.PgControlDataDataPageChecksumVersion)
+	}
+
+	if dataPageChecksumVersion == "1" {
+		options = append(options, "--data-checksums")
+	}
```
Comment (mnencia) [inline internal/cmd/manager/instance/upgrade/execute/cmd.go:325]: In postgres 18 we will have to set "--no-data-checksums" if checksums are disabled (they are enabled by default)

**Review by armru — APPROVED** [review]

**Review by armru — APPROVED** [review]

**Review by fcanovai — APPROVED** [review]
